### ISSUE TITLE
Ardb with wired tiger segfaults

### ISSUE THREAD

**Issue by ikilledthecat** [yinqiwen/ardb#144]
I was reading a large xml into ardb and suddenly it threw up a segmentation fault. I checked the logs and saw this:
```
31 [29046] 12-11 14:41:24,388 DEBUG Error find data for reason: WT_NOTFOUND: item not found
```

**Comment by ikilledthecat** [comment]
Managed to recreate the error here's the gdb backtrace
```
#0  0x000000000060cb75 in je_tcache_dalloc_small (binind=<optimized out>, ptr=<optimized out>, tcache=<optimized out>)
    at include/jemalloc/internal/tcache.h:406
#1  je_arena_dalloc (try_tcache=<optimized out>, ptr=<optimized out>, chunk=<optimized out>, arena=<optimized out>)
    at include/jemalloc/internal/arena.h:1044
#2  je_idalloct (try_tcache=<optimized out>, ptr=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:898
#3  je_iqalloct (try_tcache=<optimized out>, ptr=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:917
#4  je_iqalloc (ptr=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:924
#5  ifree (ptr=<optimized out>) at src/jemalloc.c:1233
#6  free (ptr=0x7fff94c06000) at src/jemalloc.c:1308
#7  0x00000000005532f0 in __wt_free_int (session=session@entry=0x7ffff627b280, p_arg=p_arg@entry=0x7ffff5ffeb80)
    at src/os_posix/os_alloc.c:237
#8  0x00000000005d7c71 in __free_update_list (upd=0x0, session=0x7ffff627b280) at src/btree/bt_discard.c:420
#9  __free_skip_list (ins=0x7fff9d724440, session=0x7ffff627b280) at src/btree/bt_discard.c:374
#10 __free_skip_array (entries=<optimized out>, head_arg=0x7fff9b558c00, session=0x7ffff627b280) at src/btree/bt_discard.c:355
#11 __free_page_row_leaf (page=0x7fff9ab69200, session=0x7ffff627b280) at src/btree/bt_discard.c:331
#12 __wt_page_out (session=session@entry=0x7ffff627b280, pagep=pagep@entry=0x7ffff5ffeca0) at src/btree/bt_discard.c:122
#13 0x00000000005d80e5 in __wt_ref_out (session=session@entry=0x7ffff627b280, ref=ref@entry=0x7ffff5ffeca0)
    at src/btree/bt_discard.c:32
#14 0x0000000000584d4e in __split_evict_multi (exclusive=35585, ref=0x1, session=0x7ffff627b280) at src/btree/rec_split.c:1033
#15 __wt_split_evict (session=session@entry=0x7ffff627b280, ref=ref@entry=0x7fff97aa1f10, exclusive=exclusive@entry=0)
    at src/btree/rec_split.c:1119
#16 0x0000000000584136 in __rec_page_dirty_update (exclusive=0, ref=0x7fff97aa1f10, session=0x7ffff627b280)
    at src/btree/rec_evict.c:170
#17 __wt_rec_evict (session=session@entry=0x7ffff627b280, ref=ref@entry=0x7fff97aa1f10, exclusive=exclusive@entry=0)
    at src/btree/rec_evict.c:88
#18 0x0000000000576058 in __wt_evict_page (ref=0x7fff97aa1f10, session=0x7ffff627b280) at src/btree/bt_evict.c:618
#19 __wt_evict_lru_page (session=session@entry=0x7ffff627b280, is_app=is_app@entry=0) at src/btree/bt_evict.c:1220
#20 0x0000000000576ba4 in __evict_lru_pages (is_app=<optimized out>, session=<optimized out>) at src/btree/bt_evict.c:703
#21 __evict_lru (flags=<optimized out>, session=0x7ffff627b280) at src/btree/bt_evict.c:796
#22 __evict_pass (session=0x7ffff627b280) at src/btree/bt_evict.c:486
#23 __evict_server (arg=0x7ffff627b280) at src/btree/bt_evict.c:162
#24 0x00007ffff7bc40a5 in start_thread (arg=0x7ffff5fff700) at pthread_create.c:309
#25 0x00007ffff6cb988d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by yinqiwen** [comment]
rewrite wiredtiger support in 0.9.
