### ISSUE TITLE
crash in keys

### ISSUE THREAD

**Issue by pedigree** [yinqiwen/ardb#243]
```
gateway@www:~/ardb$ gdb src/ardb-server ardb.conf 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from src/ardb-server...done.
"/home/gateway/ardb/ardb.conf" is not a core dump: File format not recognised
(gdb) run ardb.conf 
Starting program: /home/gateway/ardb/src/ardb-server ardb.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff63ff700 (LWP 11408)]
[New Thread 0x7ffff5bfe700 (LWP 11409)]
[New Thread 0x7ffff4fff700 (LWP 11410)]
[New Thread 0x7ffff43ff700 (LWP 11411)]
[New Thread 0x7ffff37ff700 (LWP 11412)]
[New Thread 0x7ffff2bff700 (LWP 11413)]
[New Thread 0x7ffff1fff700 (LWP 11414)]
[New Thread 0x7ffff11ff700 (LWP 11415)]
[New Thread 0x7ffff05ff700 (LWP 11416)]
[New Thread 0x7fffef9ff700 (LWP 11417)]
[New Thread 0x7fffeedff700 (LWP 11418)]
[New Thread 0x7fffee1ff700 (LWP 11422)]
[New Thread 0x7fffed5ff700 (LWP 11423)]
[New Thread 0x7fffec9ff700 (LWP 11426)]
[New Thread 0x7fffebdff700 (LWP 11427)]
[New Thread 0x7fffeb1ff700 (LWP 11428)]
[11404] 05-19 16:36:32,746 INFO RocksDB version: 4.3.1

[11404] 05-19 16:36:32,746 INFO Git sha rocksdb_build_git_sha:6f617270b2f538bd580ecfc4feb2a66f610f40eb
[11404] 05-19 16:36:32,746 INFO Compile date May 19 2016
[11404] 05-19 16:36:32,746 INFO DB SUMMARY

[11404] 05-19 16:36:32,746 INFO CURRENT file:  CURRENT

[11404] 05-19 16:36:32,746 INFO IDENTITY file:  IDENTITY

[11404] 05-19 16:36:32,746 INFO MANIFEST file:  MANIFEST-000012 size: 188 Bytes

[11404] 05-19 16:36:32,746 INFO SST files in /home/gateway/data/rocksdb dir, Total Num: 1, files: 000009.sst 

[11404] 05-19 16:36:32,746 INFO Write Ahead Log file in /home/gateway/data/rocksdb: 000013.log size: 0 ; 

[11404] 05-19 16:36:32,746 INFO          Options.error_if_exists: 0
[11404] 05-19 16:36:32,746 INFO        Options.create_if_missing: 1
[11404] 05-19 16:36:32,746 INFO          Options.paranoid_checks: 1
[11404] 05-19 16:36:32,746 INFO                      Options.env: 0x98e1a0
[11404] 05-19 16:36:32,746 INFO                 Options.info_log: 0x7ffff65b7d20
[11404] 05-19 16:36:32,746 INFO           Options.max_open_files: 1024
[11404] 05-19 16:36:32,746 INFO Options.max_file_opening_threads: 1
[11404] 05-19 16:36:32,746 INFO       Options.max_total_wal_size: 0
[11404] 05-19 16:36:32,746 INFO        Options.disableDataSync: 0
[11404] 05-19 16:36:32,746 INFO              Options.use_fsync: 0
[11404] 05-19 16:36:32,746 INFO      Options.max_log_file_size: 0
[11404] 05-19 16:36:32,746 INFO Options.max_manifest_file_size: 18446744073709551615
[11404] 05-19 16:36:32,746 INFO      Options.log_file_time_to_roll: 0
[11404] 05-19 16:36:32,746 INFO      Options.keep_log_file_num: 1000
[11404] 05-19 16:36:32,746 INFO   Options.recycle_log_file_num: 0
[11404] 05-19 16:36:32,746 INFO        Options.allow_os_buffer: 1
[11404] 05-19 16:36:32,746 INFO       Options.allow_mmap_reads: 0
[11404] 05-19 16:36:32,746 INFO       Options.allow_fallocate: 1
[11404] 05-19 16:36:32,747 INFO      Options.allow_mmap_writes: 0
[11404] 05-19 16:36:32,747 INFO          Options.create_missing_column_families: 0
[11404] 05-19 16:36:32,747 INFO                              Options.db_log_dir: 
[11404] 05-19 16:36:32,747 INFO                                 Options.wal_dir: /home/gateway/data/rocksdb
[11404] 05-19 16:36:32,747 INFO                Options.table_cache_numshardbits: 4
[11404] 05-19 16:36:32,747 INFO     Options.delete_obsolete_files_period_micros: 21600000000
[11404] 05-19 16:36:32,747 INFO              Options.max_background_compactions: 15
[11404] 05-19 16:36:32,747 INFO                      Options.max_subcompactions: 1
[11404] 05-19 16:36:32,747 INFO                  Options.max_background_flushes: 1
[11404] 05-19 16:36:32,747 INFO                         Options.WAL_ttl_seconds: 0
[11404] 05-19 16:36:32,747 INFO                       Options.WAL_size_limit_MB: 0
[11404] 05-19 16:36:32,747 INFO             Options.manifest_preallocation_size: 4194304
[11404] 05-19 16:36:32,747 INFO                          Options.allow_os_buffer: 1
[11404] 05-19 16:36:32,747 INFO                         Options.allow_mmap_reads: 0
[11404] 05-19 16:36:32,747 INFO                        Options.allow_mmap_writes: 0
[11404] 05-19 16:36:32,747 INFO                      Options.is_fd_close_on_exec: 1
[11404] 05-19 16:36:32,747 INFO                    Options.stats_dump_period_sec: 600
[11404] 05-19 16:36:32,747 INFO                    Options.advise_random_on_open: 1
[11404] 05-19 16:36:32,747 INFO                     Options.db_write_buffer_size: 0d
[11404] 05-19 16:36:32,747 INFO          Options.access_hint_on_compaction_start: NORMAL
[11404] 05-19 16:36:32,747 INFO   Options.new_table_reader_for_compaction_inputs: 0
[11404] 05-19 16:36:32,747 INFO                Options.compaction_readahead_size: 0d
[11404] 05-19 16:36:32,747 INFO                Options.random_access_max_buffer_size: 1048576d
[11404] 05-19 16:36:32,747 INFO               Options.writable_file_max_buffer_size: 1048576d
[11404] 05-19 16:36:32,747 INFO                       Options.use_adaptive_mutex: 0
[11404] 05-19 16:36:32,747 INFO                             Options.rate_limiter: 0x7ffff651ae80
[11404] 05-19 16:36:32,747 INFO      Options.delete_scheduler.rate_bytes_per_sec: 0
[11404] 05-19 16:36:32,747 INFO                           Options.bytes_per_sync: 1048576
[11404] 05-19 16:36:32,747 INFO                       Options.wal_bytes_per_sync: 0
[11404] 05-19 16:36:32,747 INFO                        Options.wal_recovery_mode: 0
[11404] 05-19 16:36:32,747 INFO                   Options.enable_thread_tracking: 0
[11404] 05-19 16:36:32,747 INFO                                Options.row_cache: None
[11404] 05-19 16:36:32,747 INFO        Options.wal_filter: None
[11404] 05-19 16:36:32,747 INFO Compression algorithms supported:
[11404] 05-19 16:36:32,747 INFO         Snappy supported: 1
[11404] 05-19 16:36:32,747 INFO         Zlib supported: 1
[11404] 05-19 16:36:32,747 INFO         Bzip supported: 1
[11404] 05-19 16:36:32,747 INFO         LZ4 supported: 0
[11404] 05-19 16:36:32,747 INFO Fast CRC32 supported: 1
[11404] 05-19 16:36:32,747 INFO Recovering from manifest file: MANIFEST-000012

[11404] 05-19 16:36:32,747 INFO --------------- Options for column family [default]:

[11404] 05-19 16:36:32,747 INFO               Options.comparator: rocksdb.InternalKeyComparator:ardb.comparator
[11404] 05-19 16:36:32,747 INFO           Options.merge_operator: ardb.merger
[11404] 05-19 16:36:32,747 INFO        Options.compaction_filter: None
[11404] 05-19 16:36:32,747 INFO        Options.compaction_filter_factory: ardb.compact_filter_factory
[11404] 05-19 16:36:32,747 INFO         Options.memtable_factory: SkipListFactory
[11404] 05-19 16:36:32,747 INFO            Options.table_factory: BlockBasedTable
[11404] 05-19 16:36:32,747 INFO            table_factory options:   flush_block_policy_factory: FlushBlockBySizePolicyFactory (0x7ffff64c92d8)
  cache_index_and_filter_blocks: 0
  index_type: 0
  hash_index_allow_collision: 1
  checksum: 1
  no_block_cache: 0
  block_cache: 0x7ffff659c958
  block_cache_size: 536870912
  block_cache_compressed: (nil)
  block_size: 4096
  block_size_deviation: 10
  block_restart_interval: 16
  filter_policy: rocksdb.BuiltinBloomFilter
  whole_key_filtering: 1
  skip_table_builder_flush: 0
  format_version: 0

[11404] 05-19 16:36:32,747 INFO        Options.write_buffer_size: 134217728
[11404] 05-19 16:36:32,747 INFO  Options.max_write_buffer_number: 6
[11404] 05-19 16:36:32,747 INFO        Options.compression[0]: NoCompression
[11404] 05-19 16:36:32,747 INFO        Options.compression[1]: NoCompression
[11404] 05-19 16:36:32,747 INFO        Options.compression[2]: Snappy
[11404] 05-19 16:36:32,747 INFO        Options.compression[3]: Snappy
[11404] 05-19 16:36:32,747 INFO        Options.compression[4]: Snappy
[11404] 05-19 16:36:32,747 INFO        Options.compression[5]: Snappy
[11404] 05-19 16:36:32,747 INFO        Options.compression[6]: Snappy
[11404] 05-19 16:36:32,747 INFO       Options.prefix_extractor: ardb.prefix_extractor
[11404] 05-19 16:36:32,747 INFO             Options.num_levels: 7
[11404] 05-19 16:36:32,747 INFO        Options.min_write_buffer_number_to_merge: 2
[11404] 05-19 16:36:32,747 INFO     Options.max_write_buffer_number_to_maintain: 0
[11404] 05-19 16:36:32,747 INFO            Options.compression_opts.window_bits: -14
[11404] 05-19 16:36:32,747 INFO                  Options.compression_opts.level: -1
[11404] 05-19 16:36:32,747 INFO               Options.compression_opts.strategy: 0
[11404] 05-19 16:36:32,747 INFO      Options.level0_file_num_compaction_trigger: 2
[11404] 05-19 16:36:32,747 INFO          Options.level0_slowdown_writes_trigger: 20
[11404] 05-19 16:36:32,747 INFO              Options.level0_stop_writes_trigger: 24
[11404] 05-19 16:36:32,747 INFO                   Options.target_file_size_base: 67108864
[11404] 05-19 16:36:32,747 INFO             Options.target_file_size_multiplier: 1
[11404] 05-19 16:36:32,747 INFO                Options.max_bytes_for_level_base: 536870912
[11404] 05-19 16:36:32,747 INFO Options.level_compaction_dynamic_level_bytes: 0
[11404] 05-19 16:36:32,747 INFO          Options.max_bytes_for_level_multiplier: 10
[11404] 05-19 16:36:32,747 INFO Options.max_bytes_for_level_multiplier_addtl[0]: 1
[11404] 05-19 16:36:32,747 INFO Options.max_bytes_for_level_multiplier_addtl[1]: 1
[11404] 05-19 16:36:32,747 INFO Options.max_bytes_for_level_multiplier_addtl[2]: 1
[11404] 05-19 16:36:32,747 INFO Options.max_bytes_for_level_multiplier_addtl[3]: 1
[11404] 05-19 16:36:32,747 INFO Options.max_bytes_for_level_multiplier_addtl[4]: 1
[11404] 05-19 16:36:32,747 INFO Options.max_bytes_for_level_multiplier_addtl[5]: 1
[11404] 05-19 16:36:32,748 INFO Options.max_bytes_for_level_multiplier_addtl[6]: 1
[11404] 05-19 16:36:32,748 INFO       Options.max_sequential_skip_in_iterations: 8
[11404] 05-19 16:36:32,748 INFO              Options.expanded_compaction_factor: 25
[11404] 05-19 16:36:32,748 INFO                Options.source_compaction_factor: 1
[11404] 05-19 16:36:32,748 INFO          Options.max_grandparent_overlap_factor: 10
[11404] 05-19 16:36:32,748 INFO                        Options.arena_block_size: 16777216
[11404] 05-19 16:36:32,748 INFO                       Options.soft_rate_limit: 0.00
[11404] 05-19 16:36:32,748 INFO   Options.hard_pending_compaction_bytes_limit: 0
[11404] 05-19 16:36:32,748 INFO       Options.rate_limit_delay_max_milliseconds: 1000
[11404] 05-19 16:36:32,748 INFO                Options.disable_auto_compactions: 0
[11404] 05-19 16:36:32,748 INFO                           Options.filter_deletes: 0
[11404] 05-19 16:36:32,748 INFO           Options.verify_checksums_in_compaction: 1
[11404] 05-19 16:36:32,748 INFO                         Options.compaction_style: 0
[11404] 05-19 16:36:32,748 INFO                           Options.compaction_pri: 0
[11404] 05-19 16:36:32,748 INFO  Options.compaction_options_universal.size_ratio: 1
[11404] 05-19 16:36:32,748 INFO Options.compaction_options_universal.min_merge_width: 2
[11404] 05-19 16:36:32,748 INFO Options.compaction_options_universal.max_merge_width: 4294967295
[11404] 05-19 16:36:32,748 INFO Options.compaction_options_universal.max_size_amplification_percent: 200
[11404] 05-19 16:36:32,748 INFO Options.compaction_options_universal.compression_size_percent: -1
[11404] 05-19 16:36:32,748 INFO Options.compaction_options_fifo.max_table_files_size: 1073741824
[11404] 05-19 16:36:32,748 INFO                   Options.table_properties_collectors: 
[11404] 05-19 16:36:32,748 INFO                   Options.inplace_update_support: 0
[11404] 05-19 16:36:32,748 INFO                 Options.inplace_update_num_locks: 10000
[11404] 05-19 16:36:32,748 INFO               Options.min_partial_merge_operands: 2
[11404] 05-19 16:36:32,748 INFO               Options.memtable_prefix_bloom_bits: 100000000
[11404] 05-19 16:36:32,748 INFO             Options.memtable_prefix_bloom_probes: 6
[11404] 05-19 16:36:32,748 INFO   Options.memtable_prefix_bloom_huge_page_tlb_size: 0
[11404] 05-19 16:36:32,748 INFO                           Options.bloom_locality: 1
[11404] 05-19 16:36:32,748 INFO                    Options.max_successive_merges: 0
[11404] 05-19 16:36:32,748 INFO                Options.optimize_fllters_for_hits: 0
[11404] 05-19 16:36:32,748 INFO                Options.paranoid_file_checks: 0
[11404] 05-19 16:36:32,748 INFO                Options.compaction_measure_io_stats: 0
[11404] 05-19 16:36:32,755 INFO --------------- Options for column family [0]:

[11404] 05-19 16:36:32,755 INFO               Options.comparator: rocksdb.InternalKeyComparator:ardb.comparator
[11404] 05-19 16:36:32,755 INFO           Options.merge_operator: ardb.merger
[11404] 05-19 16:36:32,755 INFO        Options.compaction_filter: None
[11404] 05-19 16:36:32,755 INFO        Options.compaction_filter_factory: ardb.compact_filter_factory
[11404] 05-19 16:36:32,755 INFO         Options.memtable_factory: SkipListFactory
[11404] 05-19 16:36:32,755 INFO            Options.table_factory: BlockBasedTable
[11404] 05-19 16:36:32,755 INFO            table_factory options:   flush_block_policy_factory: FlushBlockBySizePolicyFactory (0x7ffff64c92d8)
  cache_index_and_filter_blocks: 0
  index_type: 0
  hash_index_allow_collision: 1
  checksum: 1
  no_block_cache: 0
  block_cache: 0x7ffff659c958
  block_cache_size: 536870912
  block_cache_compressed: (nil)
  block_size: 4096
  block_size_deviation: 10
  block_restart_interval: 16
  filter_policy: rocksdb.BuiltinBloomFilter
  whole_key_filtering: 1
  skip_table_builder_flush: 0
  format_version: 0

[11404] 05-19 16:36:32,755 INFO        Options.write_buffer_size: 134217728
[11404] 05-19 16:36:32,755 INFO  Options.max_write_buffer_number: 6
[11404] 05-19 16:36:32,755 INFO        Options.compression[0]: NoCompression
[11404] 05-19 16:36:32,755 INFO        Options.compression[1]: NoCompression
[11404] 05-19 16:36:32,755 INFO        Options.compression[2]: Snappy
[11404] 05-19 16:36:32,755 INFO        Options.compression[3]: Snappy
[11404] 05-19 16:36:32,755 INFO        Options.compression[4]: Snappy
[11404] 05-19 16:36:32,755 INFO        Options.compression[5]: Snappy
[11404] 05-19 16:36:32,755 INFO        Options.compression[6]: Snappy
[11404] 05-19 16:36:32,755 INFO       Options.prefix_extractor: ardb.prefix_extractor
[11404] 05-19 16:36:32,755 INFO             Options.num_levels: 7
[11404] 05-19 16:36:32,755 INFO        Options.min_write_buffer_number_to_merge: 2
[11404] 05-19 16:36:32,755 INFO     Options.max_write_buffer_number_to_maintain: 0
[11404] 05-19 16:36:32,755 INFO            Options.compression_opts.window_bits: -14
[11404] 05-19 16:36:32,755 INFO                  Options.compression_opts.level: -1
[11404] 05-19 16:36:32,755 INFO               Options.compression_opts.strategy: 0
[11404] 05-19 16:36:32,755 INFO      Options.level0_file_num_compaction_trigger: 2
[11404] 05-19 16:36:32,755 INFO          Options.level0_slowdown_writes_trigger: 20
[11404] 05-19 16:36:32,755 INFO              Options.level0_stop_writes_trigger: 24
[11404] 05-19 16:36:32,756 INFO                   Options.target_file_size_base: 67108864
[11404] 05-19 16:36:32,756 INFO             Options.target_file_size_multiplier: 1
[11404] 05-19 16:36:32,756 INFO                Options.max_bytes_for_level_base: 536870912
[11404] 05-19 16:36:32,756 INFO Options.level_compaction_dynamic_level_bytes: 0
[11404] 05-19 16:36:32,756 INFO          Options.max_bytes_for_level_multiplier: 10
[11404] 05-19 16:36:32,756 INFO Options.max_bytes_for_level_multiplier_addtl[0]: 1
[11404] 05-19 16:36:32,756 INFO Options.max_bytes_for_level_multiplier_addtl[1]: 1
[11404] 05-19 16:36:32,756 INFO Options.max_bytes_for_level_multiplier_addtl[2]: 1
[11404] 05-19 16:36:32,756 INFO Options.max_bytes_for_level_multiplier_addtl[3]: 1
[11404] 05-19 16:36:32,756 INFO Options.max_bytes_for_level_multiplier_addtl[4]: 1
[11404] 05-19 16:36:32,756 INFO Options.max_bytes_for_level_multiplier_addtl[5]: 1
[11404] 05-19 16:36:32,756 INFO Options.max_bytes_for_level_multiplier_addtl[6]: 1
[11404] 05-19 16:36:32,756 INFO       Options.max_sequential_skip_in_iterations: 8
[11404] 05-19 16:36:32,756 INFO              Options.expanded_compaction_factor: 25
[11404] 05-19 16:36:32,756 INFO                Options.source_compaction_factor: 1
[11404] 05-19 16:36:32,756 INFO          Options.max_grandparent_overlap_factor: 10
[11404] 05-19 16:36:32,756 INFO                        Options.arena_block_size: 16777216
[11404] 05-19 16:36:32,756 INFO                       Options.soft_rate_limit: 0.00
[11404] 05-19 16:36:32,756 INFO   Options.hard_pending_compaction_bytes_limit: 0
[11404] 05-19 16:36:32,756 INFO       Options.rate_limit_delay_max_milliseconds: 1000
[11404] 05-19 16:36:32,756 INFO                Options.disable_auto_compactions: 0
[11404] 05-19 16:36:32,756 INFO                           Options.filter_deletes: 0
[11404] 05-19 16:36:32,756 INFO           Options.verify_checksums_in_compaction: 1
[11404] 05-19 16:36:32,756 INFO                         Options.compaction_style: 0
[11404] 05-19 16:36:32,756 INFO                           Options.compaction_pri: 0
[11404] 05-19 16:36:32,756 INFO  Options.compaction_options_universal.size_ratio: 1
[11404] 05-19 16:36:32,756 INFO Options.compaction_options_universal.min_merge_width: 2
[11404] 05-19 16:36:32,756 INFO Options.compaction_options_universal.max_merge_width: 4294967295
[11404] 05-19 16:36:32,756 INFO Options.compaction_options_universal.max_size_amplification_percent: 200
[11404] 05-19 16:36:32,756 INFO Options.compaction_options_universal.compression_size_percent: -1
[11404] 05-19 16:36:32,756 INFO Options.compaction_options_fifo.max_table_files_size: 1073741824
[11404] 05-19 16:36:32,756 INFO                   Options.table_properties_collectors: 
[11404] 05-19 16:36:32,756 INFO                   Options.inplace_update_support: 0
[11404] 05-19 16:36:32,756 INFO                 Options.inplace_update_num_locks: 10000
[11404] 05-19 16:36:32,756 INFO               Options.min_partial_merge_operands: 2
[11404] 05-19 16:36:32,756 INFO               Options.memtable_prefix_bloom_bits: 100000000
[11404] 05-19 16:36:32,756 INFO             Options.memtable_prefix_bloom_probes: 6
[11404] 05-19 16:36:32,756 INFO   Options.memtable_prefix_bloom_huge_page_tlb_size: 0
[11404] 05-19 16:36:32,756 INFO                           Options.bloom_locality: 1
[11404] 05-19 16:36:32,756 INFO                    Options.max_successive_merges: 0
[11404] 05-19 16:36:32,756 INFO                Options.optimize_fllters_for_hits: 0
[11404] 05-19 16:36:32,756 INFO                Options.paranoid_file_checks: 0
[11404] 05-19 16:36:32,756 INFO                Options.compaction_measure_io_stats: 0
[11404] 05-19 16:36:32,764 INFO Recovered from manifest file:/home/gateway/data/rocksdb/MANIFEST-000012 succeeded,manifest_file_number is 12, next_file_number is 14, last_sequence is 200000, log_number is 0,prev_log_number is 0,max_column_family is 1

[11404] 05-19 16:36:32,764 INFO Column family [default] (ID 0), log number is 11

[11404] 05-19 16:36:32,764 INFO Column family [0] (ID 1), log number is 11

[11404] 05-19 16:36:32,764 INFO EVENT_LOG_v1 {"time_micros": 1463675792764261, "job": 1, "event": "recovery_started", "log_files": [13]}
[11404] 05-19 16:36:32,764 INFO Recovering log #13 mode 0 skip-recovery 0
[11404] 05-19 16:36:32,764 INFO Creating manifest 15

[11404] 05-19 16:36:32,806 INFO Deleting manifest 12 current manifest 15

[11404] 05-19 16:36:32,807 INFO EVENT_LOG_v1 {"time_micros": 1463675792807063, "job": 1, "event": "recovery_finished"}
[11404] 05-19 16:36:32,809 INFO DB pointer 0x7ffff65a2800
[11404] 05-19 16:36:32,809 INFO RocksDB open column family:default success.
[11404] 05-19 16:36:32,809 INFO RocksDB open column family:0 success.
[11404] 05-19 16:36:32,809 INFO Ardb init engine:rocksdb success.
[New Thread 0x7fffe1bff700 (LWP 11429)]
[11404] 05-19 16:36:32,812 INFO Ardb will accept connections on 0.0.0.0:30000
[New Thread 0x7fffe09ff700 (LWP 11430)]
[New Thread 0x7fffdfbff700 (LWP 11431)]
[11404] 05-19 16:36:32,814 INFO Ardb started with version 0.9.0

Program received signal SIGSEGV, Segmentation fault.
ardb::Ardb::Keys (this=<optimised out>, ctx=..., cmd=...) at command/keys.cpp:396
396             while (iter->Valid())
(gdb) bt
#0  ardb::Ardb::Keys (this=<optimised out>, ctx=..., cmd=...) at command/keys.cpp:396
#1  0x000000000050cb40 in ardb::Ardb::DoCall (this=this@entry=0x7fffffffe1c0, ctx=..., setting=..., args=...) at db/db.cpp:1282
#2  0x0000000000510c2f in ardb::Ardb::Call (this=0x7fffffffe1c0, ctx=..., args=...) at db/db.cpp:1460
#3  0x000000000045d429 in ardb::RedisRequestHandler::MessageReceived (this=0x7ffff65d3540, ctx=..., e=...) at network.cpp:87
#4  0x000000000045aef3 in HandleStreamEvent (e=..., ctx=..., this=<optimised out>) at ./common/channel/channel_upstream_handler.hpp:133
#5  ardb::ChannelPipeline::SendUpstream<ardb::codec::RedisCommandFrame> (ctx=<optimised out>, e=..., this=<optimised out>) at ./common/channel/all_includes.hpp:89
#6  0x000000000045ef2e in SendUpstream<ardb::MessageEvent<ardb::codec::RedisCommandFrame> > (this=<optimised out>, this=<optimised out>, e=...)
    at ./common/channel/all_includes.hpp:164
#7  fire_message_received<ardb::codec::RedisCommandFrame> (destructor=0x0, message=0x7fffffffdde0, ctx=...) at ./common/channel/channel_helper.hpp:91
#8  ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::CallDecode (this=0x7ffff65574c0, context=..., channel=0x7ffff65b9f40, cumulation=...)
    at ./common/channel/codec/stack_frame_decoder.hpp:102
#9  0x000000000045f26f in ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::MessageReceived (this=0x7ffff65574c0, ctx=..., e=...)
    at ./common/channel/codec/stack_frame_decoder.hpp:157
#10 0x0000000000461aa3 in HandleStreamEvent (e=..., ctx=..., this=<optimised out>) at ./common/channel/channel_upstream_handler.hpp:133
#11 ardb::ChannelPipeline::SendUpstream<ardb::Buffer> (ctx=<optimised out>, e=..., this=<optimised out>) at ./common/channel/all_includes.hpp:89
#12 0x0000000000463010 in SendUpstream<ardb::MessageEvent<ardb::Buffer> > (event=..., this=0x7ffff65b9f78) at ./common/channel/all_includes.hpp:128
#13 fire_message_received<ardb::Buffer> (destructor=0x0, message=0x7ffff65b9fa8, channel=0x7ffff65b9f40) at ./common/channel/channel_helper.hpp:83
#14 ardb::Channel::OnRead (this=0x7ffff65b9f40) at common/channel/channel.cpp:550
#15 0x00000000004618cd in ardb::Channel::IOEventCallback (eventLoop=<optimised out>, fd=<optimised out>, clientData=0x7ffff65b9f40, mask=1)
    at common/channel/channel.cpp:53
#16 0x000000000049ffd0 in aeProcessEvents (eventLoop=eventLoop@entry=0x7ffff6423348, flags=flags@entry=3) at common/channel/redis/ae.c:429
#17 0x00000000004a02bb in aeMain (eventLoop=0x7ffff6423348) at common/channel/redis/ae.c:485
#18 0x000000000045b848 in ardb::Server::Start (this=this@entry=0x7fffffffe1a0) at network.cpp:296
#19 0x000000000040ae05 in main (argc=<optimised out>, argv=0x7fffffffe668) at main.cpp:92

```

To replicate,  I aborted redis-benchmark half way through the process, then connected with redis-cli

```
gateway@www:~$ redis-cli -p 30000
127.0.0.1:30000> info
# Server
ardb_version:0.9.0
redis_version:2.8.0
engine:rocksdb
ardb_home:/home/gateway
os:Linux 3.18.12-031812-generic x86_64
gcc_version:4.8.4
process_id:11404
run_id:26ee2e191c949d0492739b6a2741aa11e386a535
tcp_port:30000
listen:0.0.0.0:30000
uptime_in_seconds:16
uptime_in_days:0
executable:/home/gateway/ardb/src/ardb-server
config_file:/home/gateway/ardb/ardb.conf

# Databases
data_dir:/home/gateway/data
used_disk_space:598013576
rocksdb_version:4.3.1
rocksdb_memtable_total:25166224
rocksdb_memtable_unflushed:25166224
rocksdb_table_readers_total:0

** Compaction Stats [0] **
Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) Stall(cnt)  KeyIn KeyDrop
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      1/0       1.85   0.5      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000          0       0      0
 Sum      1/0       1.85   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000          0       0      0
 Int      0/0       0.00   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000          0       0      0
Flush(GB): cumulative 0.000, interval 0.000
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 pending_compaction_bytes, 0 memtable_compaction, 0 leveln_slowdown_soft, 0 leveln_slowdown_hard

** DB Stats **
Uptime(secs): 15.5 total, 15.5 interval
Cumulative writes: 0 writes, 0 keys, 0 batches, 0.0 writes per batch, ingest: 0.00 GB, 0.00 MB/s
Cumulative WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Cumulative stall: 00:00:0.000 H:M:S, 0.0 percent
Interval writes: 0 writes, 0 keys, 0 batches, 0.0 writes per batch, ingest: 0.00 MB, 0.00 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval stall: 00:00:0.000 H:M:S, 0.0 percent



# Clients
connected_clients:1
blocked_clients:0

# Persistence
loading:0
rdb_last_save_time:0
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_bgsave_in_progress:0
rdb_current_bgsave_time_sec:0

# CPU
used_cpu_sys:0.08
used_cpu_user:0.03

# Replication
role:master
repl_dir: /home/gateway/repl
repl_current_namespace:0
connected_slaves: 0
master_repl_offset: 76500023
repl_backlog_size: 1073741824
repl_backlog_cache_size: 104857600
repl_backlog_first_byte_offset: 0
repl_backlog_histlen: 76500024
repl_backlog_cksm: 3db3db242074e332

# Memory
used_memory_rss:36925440

# Stats
slave_sync_total_commands_processed:0
slave_sync_instantaneous_ops_per_sec:0
total_commands_processed:0
instantaneous_ops_per_sec:0
total_connections_received:1
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
pubsub_channels:0
pubsub_patterns:0
expire_scan_keys:0

# Keyspace
db0:keys=100001

127.0.0.1:30000> keys *
```
and it crashes

**Comment by pedigree** [comment]
After deleting the source and pulling / make clean, I can no longer replicate the crash.  I'll keep trying

**Comment by yinqiwen** [comment]
C++ program may crash oddly after building in an updated workspace without clean first.
