### ISSUE TITLE
 Segfault in the pipeline

### ISSUE THREAD

**Issue by animalmatsuzawa** [yinqiwen/ardb#252]
When my system was the test that you want to migrate from redis to ardb, segfault occurred .

log(Excerpt)
```
[18411] 06-06 17:28:28,473 DEBUG Process recved cmd cost 13us
[18411] 06-06 17:28:29,476 DEBUG Process recved cmd:keys crawl:*:queue
[18411] 06-06 17:28:29,476 DEBUG Process recved cmd cost 102us
[18411] 06-06 17:28:29,477 DEBUG Process recved cmd:zrange crawl:127.0.0.1:xxxxx:throttle_window 0 100
[18411] 06-06 17:28:29,477 DEBUG Process recved cmd cost 21us
[18411] 06-06 17:28:29,477 DEBUG Process recved cmd:zremrangebyscore crawl:127.0.0.1:xxxxx:throttle_window -inf 1465201708.977534
[18411] 06-06 17:28:29,477 DEBUG Process recved cmd cost 14us
[18411] 06-06 17:28:29,478 DEBUG Process recved cmd:watch crawl:127.0.0.1:xxxxx:throttle_window
[18411] 06-06 17:28:29,478 DEBUG Process recved cmd cost 6us
[18411] 06-06 17:28:29,478 DEBUG Process recved cmd:zcard crawl:127.0.0.1:xxxxx:throttle_window
[18411] 06-06 17:28:29,478 DEBUG Process recved cmd cost 9us
[18411] 06-06 17:28:29,478 DEBUG Process recved cmd:multi 
[18411] 06-06 17:28:29,478 DEBUG Process recved cmd cost 12us
[18411] 06-06 17:28:29,478 DEBUG Process recved cmd:zadd crawl:127.0.0.1:xxxxx:throttle_window 1465201709.478514 1465201709.478514
[18411] 06-06 17:28:29,478 DEBUG Process recved cmd:expire crawl:127.0.0.1:xxxxx:throttle_window 1
[18411] 06-06 17:28:29,478 DEBUG Process recved cmd:exec 
[18411] 06-06 17:28:29,478 DEBUG Process recved cmd cost 74us
[18411] 06-06 17:28:29,478 DEBUG Process recved cmd cost 26us
[18411] 06-06 17:28:29,478 DEBUG Process recved cmd cost 138us
[18411] 06-06 17:28:29,479 DEBUG HandleIOError 104:Connection reset by peer for fd:36
[18411] 06-06 17:28:29,479 DEBUG Inherit pipeline initializor from server socket.
[18411] 06-06 17:28:29,479 DEBUG Inherit pipeline finalizer from server socket.
[18411] 06-06 17:28:29,479 DEBUG Server channel(66) Accept a client channel(481) for fd:36
[18411] 06-06 17:28:29,479 DEBUG Process recved cmd:unwatch 
[18411] 06-06 17:28:29,479 DEBUG Process recved cmd cost 1us
[18411] 06-06 17:28:30,476 DEBUG Process recved cmd:zrange crawl:127.0.0.1:xxxxx:throttle_window 0 100
[18411] 06-06 17:28:30,476 DEBUG Process recved cmd cost 67us
[18411] 06-06 17:28:30,476 DEBUG Process recved cmd:zremrangebyscore crawl:127.0.0.1:xxxxx:throttle_window -inf 1465201709.976457
Segmentation fault (コアダンプ)
```
ardb.conf
```
redis-compatible-mode     yes
loglevel debug
```
gdb
```
GNU gdb (GDB) Amazon Linux (7.6.1-64.33.amzn1)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-amazon-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/src/ardb/src/ardb-server...done.
[New LWP 18434]
[New LWP 18411]
[New LWP 18412]
[New LWP 18414]
[New LWP 18413]
[New LWP 18415]
[New LWP 18423]
[New LWP 18416]
[New LWP 18424]
[New LWP 18417]
[New LWP 18425]
[New LWP 18418]
[New LWP 18426]
[New LWP 18419]
[New LWP 18427]
[New LWP 18420]
[New LWP 18430]
[New LWP 18431]
[New LWP 18432]
[New LWP 18421]
[New LWP 18422]
[New LWP 18433]
[New LWP 18429]
[New LWP 18428]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /usr/lib64/libstdc++.so.6
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/0a/90c35d3174805453ea67a785446d628e298b59.debug
Missing separate debuginfo for /lib64/libgcc_s.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/00/fa2883fb47b1327397bbf167c52f51a723d013.debug
Core was generated by `./ardb-server ../_ardb.conf -v'.
Program terminated with signal 11, Segmentation fault.
#0  ardb::Ardb::TouchWatchKey (this=this@entry=0x7ffdde2c10e0, ctx=..., key=...) at command/transaction.cpp:169
169	                    (*cit)->GetTransaction().cas = true;
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-8.12.amzn1.x86_64 glibc-2.17-106.167.amzn1.x86_64 zlib-1.2.8-7.18.amzn1.x86_64
(gdb) bt
#0  ardb::Ardb::TouchWatchKey (this=this@entry=0x7ffdde2c10e0, ctx=..., key=...) at command/transaction.cpp:169
#1  0x0000000000508d00 in ardb::Ardb::RemoveKey (this=this@entry=0x7ffdde2c10e0, ctx=..., key=...) at db/db.cpp:640
#2  0x00000000004b1ecc in ardb::Ardb::ZIterateByScore (this=0x7ffdde2c10e0, ctx=..., cmd=...) at command/t_zset.cpp:497
#3  0x0000000000509030 in ardb::Ardb::DoCall (this=this@entry=0x7ffdde2c10e0, ctx=..., setting=..., args=...)
    at db/db.cpp:1380
#4  0x000000000050cf5f in ardb::Ardb::Call (this=0x7ffdde2c10e0, ctx=..., args=...) at db/db.cpp:1558
#5  0x000000000045dbd9 in ardb::RedisRequestHandler::MessageReceived (this=0x7fd4391fdc00, ctx=..., e=...)
    at network.cpp:87
#6  0x000000000045b5a3 in HandleStreamEvent (e=..., ctx=..., this=<optimized out>)
    at ./common/channel/channel_upstream_handler.hpp:133
#7  ardb::ChannelPipeline::SendUpstream<ardb::codec::RedisCommandFrame> (ctx=<optimized out>, e=..., 
    this=<optimized out>) at ./common/channel/all_includes.hpp:89
#8  0x000000000045f6de in SendUpstream<ardb::MessageEvent<ardb::codec::RedisCommandFrame> > (this=<optimized out>, 
    this=<optimized out>, e=...) at ./common/channel/all_includes.hpp:164
#9  fire_message_received<ardb::codec::RedisCommandFrame> (destructor=0x0, message=0x7fd4361feaa0, ctx=...)
    at ./common/channel/channel_helper.hpp:91
#10 ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::CallDecode (this=0x7fd44c559680, context=..., 
    channel=0x7fd44405ce00, cumulation=...) at ./common/channel/codec/stack_frame_decoder.hpp:102
#11 0x000000000045fa1f in ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::MessageReceived (
    this=0x7fd44c559680, ctx=..., e=...) at ./common/channel/codec/stack_frame_decoder.hpp:157
#12 0x000000000046c923 in HandleStreamEvent (e=..., ctx=..., this=<optimized out>)
    at ./common/channel/channel_upstream_handler.hpp:133
#13 ardb::ChannelPipeline::SendUpstream<ardb::Buffer> (ctx=<optimized out>, e=..., this=<optimized out>)
    at ./common/channel/all_includes.hpp:89
#14 0x000000000046de2e in SendUpstream<ardb::MessageEvent<ardb::Buffer> > (event=..., this=0x7fd44405ce38)
    at ./common/channel/all_includes.hpp:128
#15 fire_message_received<ardb::Buffer> (destructor=0x0, message=0x7fd44405ce68, channel=0x7fd44405ce00)
    at ./common/channel/channel_helper.hpp:83
#16 ardb::Channel::OnRead (this=0x7fd44405ce00) at common/channel/channel.cpp:550
#17 0x000000000046c74d in ardb::Channel::IOEventCallback (eventLoop=<optimized out>, fd=<optimized out>, 
    clientData=0x7fd44405ce00, mask=1) at common/channel/channel.cpp:53
#18 0x000000000049fdd0 in aeProcessEvents (eventLoop=eventLoop@entry=0x7fd44c423348, flags=flags@entry=3)
    at common/channel/redis/ae.c:429
#19 0x00000000004a009b in aeMain (eventLoop=0x7fd44c423348) at common/channel/redis/ae.c:485
#20 0x000000000048e6e0 in ardb::Thread::ThreadFunc (data=0x7fd44c557340) at common/thread/thread.cpp:38
#21 0x00007fd44dae1dc5 in start_thread () from /lib64/libpthread.so.0
#22 0x00007fd44c9c2c9d in clone () from /lib64/libc.so.6
```

**Comment by yinqiwen** [comment]
Is these command processed synced from master?

**Comment by animalmatsuzawa** [comment]
ardb is operating alone .
python client is connecting from 2 process to ardb.

**Comment by yinqiwen** [comment]
And what's the storage engine backend?

**Comment by animalmatsuzawa** [comment]
backend is rocksdb.

**Comment by animalmatsuzawa** [comment]
```
        with self.redis_conn.pipeline() as pipe:
            try:
                pipe.watch(self.window_key)  # ---- LOCK
                value = self.redis_conn.zcard(self.window_key)
                if value < self.limit:
                    #  push value into key
                    now = time.time()
                    pipe.multi()
                    pipe.zadd(self.window_key, now, now)
                    # expire it if it hasnt been touched in a while
                    pipe.expire(self.window_key, int(self.window * 2))
                    pipe.execute()
                    return True
            except WatchError:
                # watch was changed, another thread just messed with the
                pass
```
Segfault does not occur if I change from top to bottom the client python code.
```
        try:
            self.redis_conn.watch(self.window_key)  # ---- LOCK
            value = self.redis_conn.zcard(self.window_key)
            if value < self.limit:
                # push value into key
                now = time.time()
                self.redis_conn.zadd(self.window_key, now, now)
                self.redis_conn.expire(self.window_key, int(self.window * 2))
                return True
        except WatchError:
             # watch was changed, another thread just messed with the
             pass
```

**Comment by yinqiwen** [comment]
It's a transaction related issue, i'm trying to recreate it.

**Comment by yinqiwen** [comment]
fixed by last commit.

**Comment by animalmatsuzawa** [comment]
Thank you for quick response.
This works, I will continue to test.
