### ISSUE TITLE
Segmentation fault in transaction.cpp:224

### ISSUE THREAD

**Issue by animalmatsuzawa** [yinqiwen/ardb#262]
segfault has occurred and put a high load.

os:ubuntu 14.04
backend is rocksdb.
ardb is operating alone .
python client is connecting from 16 process to ardb.

core file(gziped)
[core-ardb-server-11-0-0-6463-1467370166.gz](https://github.com/yinqiwen/ardb/files/343310/core-ardb-server-11-0-0-6463-1467370166.gz)

log
```
[6463] 07-01 19:49:26,514 DEBUG Process recved cmd cost 32us
[6463] 07-01 19:49:26,514 DEBUG Process recved cmd:zadd link:amazonaws.com:queue 39 �}q(UbodyqT�
[6463] 07-01 19:49:26,514 DEBUG Process recved cmd:get link:http_cache::dc2835447611b8f1e62af94e7ecd520c49aae171_data
[6463] 07-01 19:49:26,514 DEBUG Process recved cmd cost 21us
[6463] 07-01 19:49:26,517 DEBUG Process recved cmd cost 4290us
[6463] 07-01 19:49:26,517 DEBUG Process recved cmd cost 10005us
[6463] 07-01 19:49:26,517 DEBUG Process recved cmd:get cookiejar:splash
[6463] 07-01 19:49:26,517 DEBUG Process recved cmd cost 9us
[6463] 07-01 19:49:26,517 DEBUG Process recved cmd cost 3280us
[6463] 07-01 19:49:26,517 DEBUG Process recved cmd:zadd stats:crawler:ip-10-10-0-150:link:200:3600 1467370166.09886 1467370166.09886
[6463] 07-01 19:49:26,517 DEBUG Process recved cmd:multi 
[6463] 07-01 19:49:26,517 DEBUG Process recved cmd cost 1us
[6463] 07-01 19:49:26,517 DEBUG Process recved cmd:zrange link:amazonaws.com:queue 0 0
[6463] 07-01 19:49:26,517 DEBUG Process recved cmd:zremrangebyrank link:amazonaws.com:queue 0 0
[6463] 07-01 19:49:26,518 DEBUG Process recved cmd:exec 
[6463] 07-01 19:49:26,518 DEBUG Process recved cmd:get cookiejar:splash
[6463] 07-01 19:49:26,518 DEBUG Process recved cmd cost 8us
[6463] 07-01 19:49:26,518 DEBUG Process recved cmd cost 337us
[6463] 07-01 19:49:26,518 DEBUG Process recved cmd:get cookiejar:splash
[6463] 07-01 19:49:26,518 DEBUG Process recved cmd cost 10us
[6463] 07-01 19:49:26,519 DEBUG Process recved cmd:sadd link:dupefilter:abc123 a998f1dee7d9a33ed3faaa0e0e1d2566634316e7
[6463] 07-01 19:49:26,519 DEBUG Process recved cmd cost 70us
[6463] 07-01 19:49:26,519 DEBUG Process recved cmd:pfadd stats:crawler:ip-10-10-0-150:link:200:lifetime http://xiwayy2kn32bo3ko.onion/test/read.cgi/ura/1386407696/55n2001467370166.1
[6463] 07-01 19:49:26,519 DEBUG Process recved cmd cost 72us
[6463] 07-01 19:49:26,519 DEBUG Process recved cmd:sadd link:dupefilter:abc123 54a73cdda8ac82e8b0e87291c0511ce819f66fcd
[6463] 07-01 19:49:26,520 DEBUG Process recved cmd:sadd link:dupefilter:abc123 12345b6eafba15f89051a0ca2908750d628bd4bf
[6463] 07-01 19:49:26,520 DEBUG Process recved cmd:get link:http_cache::dfd936c81cd5cfff303888fd3d18fb44366389be_data
[6463] 07-01 19:49:26,520 DEBUG Process recved cmd cost 18us
[6463] 07-01 19:49:26,520 DEBUG Process recved cmd cost 399us
[6463] 07-01 19:49:26,520 DEBUG Process recved cmd cost 461us
[6463] 07-01 19:49:26,520 DEBUG Process recved cmd:zremrangebyscore link:52.192.108.225:amazonaws.com:throttle_window -inf 1467370106.106513
[6463] 07-01 19:49:26,520 DEBUG Process recved cmd cost 23us
[6463] 07-01 19:49:26,521 DEBUG Process recved cmd:sismember link:blacklist testapp||abc123
[6463] 07-01 19:49:26,521 DEBUG Process recved cmd cost 21us
[6463] 07-01 19:49:26,521 DEBUG Process recved cmd:zadd stats:crawler:ip-10-10-0-150:link:200:604800 1467370166.102047 1467370166.102047
[6463] 07-01 19:49:26,521 DEBUG Process recved cmd cost 73us
[6463] 07-01 19:49:26,521 DEBUG Process recved cmd:zadd link:amazonaws.com:queue 39 �}q(UbodyqT�
[6463] 07-01 19:49:26,521 DEBUG Process recved cmd:multi 
[6463] 07-01 19:49:26,521 DEBUG Process recved cmd cost 1us
[6463] 07-01 19:49:26,522 DEBUG Process recved cmd:zrange link:amazonaws.com:queue 0 0
[6463] 07-01 19:49:26,522 DEBUG Process recved cmd:zremrangebyrank link:amazonaws.com:queue 0 0
[6463] 07-01 19:49:26,522 DEBUG Process recved cmd:exec 
[6463] 07-01 19:49:26,522 DEBUG Process recved cmd cost 4716us
[6463] 07-01 19:49:26,522 DEBUG Process recved cmd cost 1083us
[6463] 07-01 19:49:26,523 DEBUG Process recved cmd cost 1072us
[6463] 07-01 19:49:26,523 DEBUG Process recved cmd:zremrangebyscore link:52.192.108.225:onion.:throttle_window -inf 1467370106.109242
[6463] 07-01 19:49:26,524 DEBUG Process recved cmd cost 25us
[6463] 07-01 19:49:26,524 DEBUG Process recved cmd:multi 
[6463] 07-01 19:49:26,524 DEBUG Process recved cmd cost 1us
[6463] 07-01 19:49:26,524 DEBUG Process recved cmd:zrange link:onion.:queue 0 0
[6463] 07-01 19:49:26,524 DEBUG Process recved cmd:zremrangebyrank link:onion.:queue 0 0
[6463] 07-01 19:49:26,525 DEBUG Process recved cmd:exec 
[6463] 07-01 19:49:26,524 DEBUG Process recved cmd cost 1309us
[6463] 07-01 19:49:26,525 DEBUG Process recved cmd cost 7268us
[6463] 07-01 19:49:26,525 DEBUG Process recved cmd:get link:http_cache::900e990d656ab234cad50eebddfb5cf210182228_data
[6463] 07-01 19:49:26,525 DEBUG Process recved cmd cost 19us
[6463] 07-01 19:49:26,525 DEBUG Process recved cmd:multi 
[6463] 07-01 19:49:26,525 DEBUG Process recved cmd cost 1us
[6463] 07-01 19:49:26,525 DEBUG Process recved cmd:zrange link:amazonaws.com:queue 0 0
[6463] 07-01 19:49:26,525 DEBUG Process recved cmd:zremrangebyrank link:amazonaws.com:queue 0 0
[6463] 07-01 19:49:26,525 DEBUG Process recved cmd:exec 
[6463] 07-01 19:49:26,525 DEBUG Process recved cmd:get cookiejar:splash
[6463] 07-01 19:49:26,525 DEBUG Process recved cmd cost 8us
[6463] 07-01 19:49:26,527 DEBUG Process recved cmd:get link:http_cache::42b53e60bd7fae1634b490f5aba647db572cec91_data
[6463] 07-01 19:49:26,527 DEBUG Process recved cmd cost 19us
[6463] 07-01 19:49:26,531 DEBUG Process recved cmd cost 7817us
[6463] 07-01 19:49:26,534 DEBUG Process recved cmd cost 11836us
[6463] 07-01 19:49:26,533 DEBUG Process recved cmd cost 8101us
[6463] 07-01 19:49:26,536 DEBUG Process recved cmd cost 10864us
[6463] 07-01 19:49:26,538 DEBUG Process recved cmd:sadd link:dupefilter:abc123 500864f1b0a6951f079fb245dce936d2fa589626
[6463] 07-01 19:49:26,538 DEBUG Process recved cmd cost 112us
[6463] 07-01 19:49:26,539 DEBUG Process recved cmd:sadd link:dupefilter:abc123 7077160d8e368dae58914cef860bc753dbb80da8
[6463] 07-01 19:49:26,539 DEBUG Process recved cmd cost 90us
[6463] 07-01 19:49:26,541 DEBUG Process recved cmd:sadd link:dupefilter:abc123 4e6ec761ed931d168c56ebd56460ba308e8e2976
[6463] 07-01 19:49:26,541 DEBUG Process recved cmd cost 96us
[6463] 07-01 19:49:26,541 DEBUG Process recved cmd cost 5409us
[6463] 07-01 19:49:26,541 DEBUG Process recved cmd cost 16366us
[6463] 07-01 19:49:26,541 DEBUG Process recved cmd:sismember link:blacklist testapp||abc123
[6463] 07-01 19:49:26,541 DEBUG Process recved cmd cost 22us
[6463] 07-01 19:49:26,542 DEBUG Process recved cmd:sismember link:blacklist testapp||abc123
[6463] 07-01 19:49:26,542 DEBUG Process recved cmd cost 18us
[6463] 07-01 19:49:26,542 DEBUG Process recved cmd:zremrangebyscore link:52.192.108.225:amazonaws.com:throttle_window -inf 1467370106.114249
[6463] 07-01 19:49:26,542 DEBUG Process recved cmd cost 25us
[6463] 07-01 19:49:26,542 DEBUG Process recved cmd:zremrangebyscore link:52.192.108.225:onion.:throttle_window -inf 1467370106.111727
[6463] 07-01 19:49:26,542 DEBUG Process recved cmd cost 21us
[6463] 07-01 19:49:26,542 DEBUG Process recved cmd:sadd link:dupefilter:abc123 31f0863751d0f988f2a43f9b3f54e007ee5c863a
[6463] 07-01 19:49:26,542 DEBUG Process recved cmd cost 103us
[6463] 07-01 19:49:26,542 DEBUG Process recved cmd:zadd link:amazonaws.com:queue 39 �}q(UbodyqT�
[6463] 07-01 19:49:26,542 DEBUG Process recved cmd cost 170us
[6463] 07-01 19:49:26,542 DEBUG Process recved cmd:zadd link:amazonaws.com:queue 39 �}q(UbodyqT�
[6463] 07-01 19:49:26,543 DEBUG Process recved cmd cost 174us
[6463] 07-01 19:49:26,543 DEBUG Process recved cmd:multi 
[6463] 07-01 19:49:26,543 DEBUG Process recved cmd cost 0us
[6463] 07-01 19:49:26,543 DEBUG Process recved cmd:zrange link:onion.:queue 0 0
[6463] 07-01 19:49:26,543 DEBUG Process recved cmd:zremrangebyrank link:onion.:queue 0 0
[6463] 07-01 19:49:26,543 DEBUG Process recved cmd:exec 
[6463] 07-01 19:49:26,543 DEBUG Process recved cmd:get link:http_cache::464a39a4684ca504bc639db61baff1c12c22f457_data
[6463] 07-01 19:49:26,543 DEBUG Process recved cmd cost 22us
[6463] 07-01 19:49:26,543 DEBUG Process recved cmd:sadd link:dupefilter:abc123 c3cc0124ff9552e23dfb9fa4f40f7326cbb6dc9e
[6463] 07-01 19:49:26,543 DEBUG Process recved cmd cost 9405us
[6463] 07-01 19:49:26,543 DEBUG Process recved cmd cost 103us
[6463] 07-01 19:49:26,544 DEBUG Process recved cmd cost 18958us
[6463] 07-01 19:49:26,544 DEBUG Process recved cmd:watch link:http_cache::7633a63ea9354d8d0a8d752ebc63a42ec1366e51_data
[6463] 07-01 19:49:26,544 DEBUG Process recved cmd cost 13us
[6463] 07-01 19:49:26,544 DEBUG Process recved cmd:sadd link:dupefilter:abc123 16cf65ab4dc32f2ecba859ca86876a56512ac6c1
[6463] 07-01 19:49:26,544 DEBUG Process recved cmd cost 73us
[6463] 07-01 19:49:26,544 DEBUG Process recved cmd:get link:http_cache::42b53e60bd7fae1634b490f5aba647db572cec91_data
[6463] 07-01 19:49:26,544 DEBUG Process recved cmd cost 18us
[6463] 07-01 19:49:26,545 DEBUG Process recved cmd:sadd link:dupefilter:abc123 6772c16528d0556141003b0f0ac7d753e8f94d60
[6463] 07-01 19:49:26,545 DEBUG Process recved cmd cost 90us
[6463] 07-01 19:49:26,545 DEBUG Process recved cmd:set link:http_cache::7633a63ea9354d8d0a8d752ebc63a42ec1366e51_data �}q(UstatusqK�UurlqX>
[6463] 07-01 19:49:26,545 DEBUG Process recved cmd cost 79us
[6463] 07-01 19:49:26,545 DEBUG Process recved cmd:zremrangebyscore link:52.192.108.225:onion.:throttle_window -inf 1467370106.131275
[6463] 07-01 19:49:26,545 DEBUG Process recved cmd cost 22us
[6463] 07-01 19:49:26,546 DEBUG Process recved cmd:unwatch 
[6463] 07-01 19:49:26,546 WARN No found in global watch contexts
[6463] 07-01 19:49:26,546 DEBUG Process recved cmd:multi 
[6463] 07-01 19:49:26,546 DEBUG Process recved cmd cost 1us
[6463] 07-01 19:49:26,546 DEBUG Process recved cmd:zrange link:onion.:queue 0 0
[6463] 07-01 19:49:26,546 DEBUG Process recved cmd:zremrangebyrank link:onion.:queue 0 0
[6463] 07-01 19:49:26,546 DEBUG Process recved cmd:exec 
[6463] 07-01 19:49:26,550 WARN No found in global watch contexts
[6463] 07-01 19:49:26,550 WARN No found in global watch contexts
[6463] 07-01 19:49:26,550 WARN No found in global watch contexts
[6463] 07-01 19:49:26,550 WARN No found in global watch contexts
[6463] 07-01 19:49:26,550 WARN No found in global watch contexts
[6463] 07-01 19:49:26,550 WARN No found in global watch contexts
[6463] 07-01 19:49:26,550 DEBUG Process recved cmd cost 4584us
Segmentation fault (core dumped)
```
gdb
```
root@ip-10-10-0-198:/tmp# gdb /usr/local/bin/ardb-server core-ardb-server-11-0-0-6463-1467370166
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/ardb-server...done.
[New LWP 6487]
[New LWP 6463]
[New LWP 6490]
[New LWP 6464]
[New LWP 6465]
[New LWP 6466]
[New LWP 6467]
[New LWP 6471]
[New LWP 6468]
[New LWP 6484]
[New LWP 6469]
[New LWP 6485]
[New LWP 6470]
[New LWP 6482]
[New LWP 6472]
[New LWP 6473]
[New LWP 6481]
[New LWP 6474]
[New LWP 6475]
[New LWP 6476]
[New LWP 6477]
[New LWP 6478]
[New LWP 6479]
[New LWP 6480]
[New LWP 6483]
[New LWP 6486]
[New LWP 6489]
[New LWP 6488]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/ardb-server /etc/ardb/ardb.conf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ardb::Ardb::UnwatchKeys (this=this@entry=0x7ffc644def80, ctx=...) at command/transaction.cpp:224
224	        if (m_watched_ctxs->empty())
(gdb) bt
#0  ardb::Ardb::UnwatchKeys (this=this@entry=0x7ffc644def80, ctx=...) at command/transaction.cpp:224
#1  0x00000000004f2043 in ardb::Ardb::Exec (this=0x7ffc644def80, ctx=..., cmd=...)
    at command/transaction.cpp:82
#2  0x000000000050876e in ardb::Ardb::DoCall (this=this@entry=0x7ffc644def80, ctx=..., setting=..., 
    args=...) at db/db.cpp:1395
#3  0x000000000050c690 in ardb::Ardb::Call (this=0x7ffc644def80, ctx=..., args=...) at db/db.cpp:1574
#4  0x000000000045e411 in ardb::RedisRequestHandler::MessageReceived (this=0x7fe6987f4280, ctx=..., 
    e=...) at network.cpp:86
#5  0x000000000045bdb3 in HandleStreamEvent (e=..., ctx=..., this=<optimized out>)
    at ./common/channel/channel_upstream_handler.hpp:133
#6  ardb::ChannelPipeline::SendUpstream<ardb::codec::RedisCommandFrame> (ctx=<optimized out>, e=..., 
    this=<optimized out>) at ./common/channel/all_includes.hpp:89
#7  0x000000000045ff3e in SendUpstream<ardb::MessageEvent<ardb::codec::RedisCommandFrame> > (
    this=<optimized out>, this=<optimized out>, e=...) at ./common/channel/all_includes.hpp:164
#8  fire_message_received<ardb::codec::RedisCommandFrame> (destructor=0x0, message=0x7fe67d9f7a70, 
    ctx=...) at ./common/channel/channel_helper.hpp:91
#9  ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::CallDecode (this=0x7fe69872fc00, 
    context=..., channel=0x7fe6987cb180, cumulation=...)
    at ./common/channel/codec/stack_frame_decoder.hpp:102
#10 0x000000000046027f in ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::MessageReceived (this=0x7fe69872fc00, ctx=..., e=...) at ./common/channel/codec/stack_frame_decoder.hpp:157
#11 0x0000000000462bf3 in HandleStreamEvent (e=..., ctx=..., this=<optimized out>)
    at ./common/channel/channel_upstream_handler.hpp:133
#12 ardb::ChannelPipeline::SendUpstream<ardb::Buffer> (ctx=<optimized out>, e=..., 
    this=<optimized out>) at ./common/channel/all_includes.hpp:89
#13 0x0000000000464110 in SendUpstream<ardb::MessageEvent<ardb::Buffer> > (event=..., 
    this=0x7fe6987cb1b8) at ./common/channel/all_includes.hpp:128
#14 fire_message_received<ardb::Buffer> (destructor=0x0, message=0x7fe6987cb1e8, 
    channel=0x7fe6987cb180) at ./common/channel/channel_helper.hpp:83
#15 ardb::Channel::OnRead (this=0x7fe6987cb180) at common/channel/channel.cpp:550
#16 0x0000000000462a1d in ardb::Channel::IOEventCallback (eventLoop=<optimized out>, 
---Type <return> to continue, or q <return> to quit---
    fd=<optimized out>, clientData=0x7fe6987cb180, mask=1) at common/channel/channel.cpp:53
#17 0x00000000004a1d30 in aeProcessEvents (eventLoop=eventLoop@entry=0x7fe698623488, 
    flags=flags@entry=3) at common/channel/redis/ae.c:429
#18 0x00000000004a201b in aeMain (eventLoop=0x7fe698623488) at common/channel/redis/ae.c:485
#19 0x0000000000490610 in ardb::Thread::ThreadFunc (data=0x7fe6986bcb80) at common/thread/thread.cpp:38
#20 0x00007fe699ad8184 in start_thread (arg=0x7fe67d9f8700) at pthread_create.c:312
#21 0x00007fe698bc437d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) 
```

**Comment by yinqiwen** [comment]
Thanks for this bug report, it's fixed by last commit.

**Comment by animalmatsuzawa** [comment]
Thank you for quick response.
This works, I will continue to test.
