### ISSUE TITLE
segfault when using scard

### ISSUE THREAD

**Issue by maros** [yinqiwen/ardb#306]
Whenever I use some set-related commands i get a SIGSEGV (scard, smembers or even dump on a set key)

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc6bf4700 (LWP 27181)]
ardb::codec::RedisReply::MemberAt (this=this@entry=0x7fffc6021a40, i=i@entry=0) at common/channel/codec/redis_reply.cpp:150
150                 return *(elements->at(i));
(gdb)
(gdb) p i
$1 = 0
(gdb) p elements
$2 = (std::deque<ardb::codec::RedisReply*, std::allocator<ardb::codec::RedisReply*> > *) 0x0
(gdb)
```
I'm running on b3cb76f4cef6054a2a3f3ee086a7d09c281d3542 using rocksdb.

**Comment by maros** [comment]
And here is the backtrace
```
(gdb) backtrace
#0  ardb::codec::RedisReply::MemberAt (this=this@entry=0x7fffc6021a40, i=i@entry=0) at common/channel/codec/redis_reply.cpp:150
#1  0x00000000004f4e37 in ardb::Ardb::SMembers (this=0x7fffffffe2d0, ctx=..., cmd=...) at command/t_set.cpp:185
#2  0x0000000000559efa in ardb::Ardb::DoCall (this=this@entry=0x7fffffffe2d0, ctx=..., setting=..., args=...) at db/db.cpp:1395
#3  0x000000000055c039 in ardb::Ardb::Call (this=0x7fffffffe2d0, ctx=..., args=...) at db/db.cpp:1557
#4  0x0000000000497f32 in ardb::RedisRequestHandler::MessageReceived (this=0x7ffff6591380, ctx=..., e=...) at network.cpp:130
#5  0x0000000000492b73 in HandleStreamEvent (e=..., ctx=..., this=<optimized out>) at ./common/channel/channel_upstream_handler.hpp:133
#6  ardb::ChannelPipeline::SendUpstream<ardb::codec::RedisCommandFrame> (ctx=<optimized out>, e=..., this=<optimized out>)
    at ./common/channel/all_includes.hpp:89
#7  0x0000000000498f36 in SendUpstream<ardb::MessageEvent<ardb::codec::RedisCommandFrame> > (this=<optimized out>, this=<optimized out>,
    e=...) at ./common/channel/all_includes.hpp:164
#8  fire_message_received<ardb::codec::RedisCommandFrame> (destructor=0x0, message=0x7fffc6bf3a90, ctx=...)
    at ./common/channel/channel_helper.hpp:91
#9  ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::CallDecode (this=0x7ffff6516c00, context=..., channel=
    0x7fffb3bfc900, cumulation=...) at ./common/channel/codec/stack_frame_decoder.hpp:102
#10 0x00000000004991f9 in ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::MessageReceived (this=0x7ffff6516c00, ctx=...,
    e=...) at ./common/channel/codec/stack_frame_decoder.hpp:157
#11 0x000000000049b943 in HandleStreamEvent (e=..., ctx=..., this=<optimized out>) at ./common/channel/channel_upstream_handler.hpp:133
#12 ardb::ChannelPipeline::SendUpstream<ardb::Buffer> (ctx=<optimized out>, e=..., this=<optimized out>)
    at ./common/channel/all_includes.hpp:89
#13 0x000000000049d350 in SendUpstream<ardb::MessageEvent<ardb::Buffer> > (event=..., this=0x7fffb3bfc938)
    at ./common/channel/all_includes.hpp:128
#14 fire_message_received<ardb::Buffer> (destructor=0x0, message=0x7fffb3bfc968, channel=0x7fffb3bfc900)
    at ./common/channel/channel_helper.hpp:83
#15 ardb::Channel::OnRead (this=0x7fffb3bfc900) at common/channel/channel.cpp:560
#16 0x000000000049b9ad in ardb::Channel::IOEventCallback (eventLoop=<optimized out>, fd=<optimized out>, clientData=0x7fffb3bfc900,
    mask=1) at common/channel/channel.cpp:53
#17 0x00000000004dadd4 in aeProcessEvents (eventLoop=0x7fffc6021a40, eventLoop@entry=0x7fffea3961b8, flags=0, flags@entry=3)
    at common/channel/redis/ae.c:429
#18 0x00000000004db16b in aeMain (eventLoop=0x7fffea3961b8) at common/channel/redis/ae.c:485
#19 0x00000000004c99f0 in ardb::Thread::ThreadFunc (data=0x7fffea2c5cf0) at common/thread/thread.cpp:38
#20 0x00007ffff7bc70a4 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#21 0x00007ffff6aa762d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by yinqiwen** [comment]
fixed in https://github.com/yinqiwen/ardb/commit/58f3875b95ff96d3bb40332e47c60e9e06a24f0f

**Comment by maros** [comment]
yes, this fixed the issue. Thank you
