### ISSUE TITLE
crash on MONITOR command

### ISSUE THREAD

**Issue by mb78** [yinqiwen/ardb#307]
The redis-server in 0.9.1 (might be applicable to the newest code) went down after few seconds from MONITOR command (rhel7, x86_74). ctx.client was 0 for some reason, didnt debug it further.

Simple condition helped, https://github.com/mb78/ardb/commit/5e67d18259d4e5f495d8e6287983eb4530b02ed2.

Backtrace
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `ardb-server /opt/pcf/controller/etc/ardb.conf'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004d30dd in ardb::Ardb::FeedMonitors(ardb::Context&, ardb::Data const&, ardb::codec::RedisCommandFrame&) ()
Missing separate debuginfos, use: debuginfo-install ardb-0.9-1.x86_64
(gdb) bt
#0  0x00000000004d30dd in ardb::Ardb::FeedMonitors(ardb::Context&, ardb::Data const&, ardb::codec::RedisCommandFrame&) ()
#1  0x0000000000506c27 in ardb::Ardb::DoCall(ardb::Context&, ardb::Ardb::RedisCommandHandlerSetting&, ardb::codec::RedisCommandFrame&) ()
#2  0x000000000050aa20 in ardb::Ardb::Call(ardb::Context&, ardb::codec::RedisCommandFrame&) ()
#3  0x0000000000519654 in ardb::DBWriterWorker::Run() ()
#4  0x000000000048f460 in ardb::Thread::ThreadFunc(void*) ()
#5  0x00007fbcddb9cdc5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fbcdca7b1cd in clone () from /lib64/libc.so.6
```

**Comment by yinqiwen** [comment]
is the 'monitor' execute in lua script?

**Comment by mb78** [comment]
no, it was just
```$> redis-cli monitor```

**Comment by yinqiwen** [comment]
is the 'monitor' executed on a slave instance?

**Comment by mb78** [comment]
yes, it was a slave of redis 3.0.7

**Comment by yinqiwen** [comment]
fixed in https://github.com/yinqiwen/ardb/commit/c5084ce2846c7d6a94b23fa6e6bb98aef7e31789
