### ISSUE TITLE
Segfault report

### ISSUE THREAD

**Issue by maros** [yinqiwen/ardb#308]
using c5084ce2846c7d6a94b23fa6e6bb98aef7e31789

```
[New Thread 0x7fffe2fff700 (LWP 19997)]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[New Thread 0x7fffe27fe700 (LWP 19998)]

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe2fff700 (LWP 19997)]
0x00007ffff69f4067 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) backtrace
#0  0x00007ffff69f4067 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff69f5448 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff72e1b3d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff72dfbb6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff72dfc01 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff72dfe19 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff72e0339 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff733fe99 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff733ff14 in std::string::_M_mutate(unsigned long, unsigned long, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff73400c6 in std::string::_M_leak_hard() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00000000004c258f in _M_leak (this=0x494298) at /usr/include/c++/4.9/bits/basic_string.h:317
#11 operator[] (__pos=0, this=0x494298) at /usr/include/c++/4.9/bits/basic_string.h:860
#12 ardb::lower_string (
    str="\000D\000\000\000\274\006\005\000\250\313\361\377j\002\000\000\000B\016\020\216\002B\016\030\215\003E\016 \214\004A\016(\206\005F\016\060\203\006P\016@\002\221\n\016\060D\016(A\016 B\016\030B\016\020B\016\bD\v\000\000\000\000\000D\000\000\000\004\a\005\000\320\315\361\377j\002\000\000\000B\016\020\216\002B\016\030\215\003E\016 \214\004A\016(\206\005F\016\060\203\006P\016@\002\221\n\016\060D\016(A\016 B\016\030B\016\020B\016\bD\v\000\000\000\000\000D\000\000\000L\a\005\000\370\317\361\377j\002\000\000\000B\016\020\216\002B\016\030\215\003E\016 \214\004A\016(\206\005F\016\060\203\006P\016@\002\221\n\016\060D\016(A\016"...) at common/util/string_helper.cpp:230
#13 0x000000000055b33a in ardb::Ardb::FindRedisCommandHandlerSetting (this=this@entry=0x7fffffffe6f0, args=...) at db/db.cpp:1424
#14 0x000000000055bb67 in ardb::Ardb::Call (this=0x7fffffffe6f0, ctx=..., args=...) at db/db.cpp:1437
#15 0x00000000005573cc in Call (cmd=..., this=0x7ffff656da80) at db/db_utils.cpp:84
#16 ardb::DBWriterWorker::Run (this=0x7ffff656da80) at db/db_utils.cpp:100
#17 0x00000000004c99f0 in ardb::Thread::ThreadFunc (data=0x7ffff656da80) at common/thread/thread.cpp:38
#18 0x00007ffff7bc70a4 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#19 0x00007ffff6aa762d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by yinqiwen** [comment]
u need 'make clean' first to rebuild

**Comment by maros** [comment]
yes, that fixed this crash. Sorry for this wrong bug report
