### ISSUE TITLE
Send info to slave which is syncing from master will make it crash

### ISSUE THREAD

**Issue by monsterxx03** [yinqiwen/ardb#315]
Master and slave are both ardb.

when slave is loading backup synced from master, if send a `info` command to slave, it will crash.

It happen after log: `Start loading snapshot:/mnt/ardb/backup/sync-rocksdb-backup.1835145290.58744817534011532.1487750314`

If send `get a` to slave, it will return `LOADING Ardb is loading the snapshot file.` normally.

**Comment by yinqiwen** [comment]
any found in gdb stack trace?

**Comment by monsterxx03** [comment]
```
#0  0x000000000056cc9e in ardb::RocksDBEngine::Stats (this=0x7fa45b72b900, ctx=..., all="rocksdb_version:5.0.2\r\n") at db/rocksdb/rocksdb_engine.cpp:1313
#1  0x00000000004c154b in ardb::Ardb::FillInfoResponse (this=this@entry=0x7ffca344f830, ctx=..., section="default",
    info="# Server\r\nardb_version:0.9.4\r\nredis_version:2.8.0\r\nengine:rocksdb\r\nardb_home:/home/vagrant/test1\r\nos:Linux 4.4.0-38-generic x86_64\r\ngcc_version:5.4.0\r
\nprocess_id:28756\r\nrun_id:cbd4d830254bed7fe3c16418"...) at command/server.cpp:230
#2  0x00000000004c2f9a in ardb::Ardb::Info (this=0x7ffca344f830, ctx=..., cmd=...) at command/server.cpp:449
#3  0x000000000053b84a in ardb::Ardb::DoCall (this=this@entry=0x7ffca344f830, ctx=..., setting=..., args=...) at db/db.cpp:1395
#4  0x0000000000541017 in ardb::Ardb::Call (this=0x7ffca344f830, ctx=..., args=...) at db/db.cpp:1557
#5  0x00000000004746bd in ardb::RedisRequestHandler::MessageReceived (e=..., ctx=..., this=0x7fa45b73c600) at network.cpp:130
#6  ardb::ChannelUpstreamHandler<ardb::codec::RedisCommandFrame>::HandleStreamEvent (e=..., ctx=..., this=0x7fa45b73c600)
    at ./common/channel/channel_upstream_handler.hpp:133
#7  ardb::ChannelPipeline::SendUpstream<ardb::codec::RedisCommandFrame> (ctx=<optimized out>, e=..., this=<optimized out>) at ./common/channel/all_includes.hpp:89
#8  0x0000000000479420 in ardb::ChannelHandlerContext::SendUpstream<ardb::MessageEvent<ardb::codec::RedisCommandFrame> > (this=0x7fa454087810, this=0x7fa454087810, e=...)
    at ./common/channel/all_includes.hpp:164
#9  ardb::fire_message_received<ardb::codec::RedisCommandFrame> (destructor=0x0, message=0x7fa4451fea00, ctx=...) at ./common/channel/channel_helper.hpp:91
#10 ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::CallDecode (this=0x7fa4540a68c0, context=..., channel=0x7fa45b747b80, cumulation=...)
    at ./common/channel/codec/stack_frame_decoder.hpp:102
#11 0x0000000000479f68 in ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::MessageReceived (this=0x7fa4540a68c0, ctx=..., e=...)
    at ./common/channel/codec/stack_frame_decoder.hpp:157
#12 0x000000000047c5c3 in ardb::ChannelUpstreamHandler<ardb::Buffer>::HandleStreamEvent (e=..., ctx=..., this=<optimized out>)
    at ./common/channel/channel_upstream_handler.hpp:133
#13 ardb::ChannelPipeline::SendUpstream<ardb::Buffer> (ctx=<optimized out>, e=..., this=0x7fa45b747bb8) at ./common/channel/all_includes.hpp:89
#14 0x000000000047d882 in ardb::ChannelPipeline::SendUpstream<ardb::MessageEvent<ardb::Buffer> > (event=..., this=0x7fa45b747bb8) at ./common/channel/all_includes.hpp:128
#15 ardb::fire_message_received<ardb::Buffer> (destructor=0x0, message=0x7fa45b747be8, channel=0x7fa45b747b80) at ./common/channel/channel_helper.hpp:83
#16 ardb::Channel::OnRead (this=0x7fa45b747b80) at common/channel/channel.cpp:560
#17 0x000000000047c62d in ardb::Channel::IOEventCallback (eventLoop=<optimized out>, fd=<optimized out>, clientData=0x7fa45b747b80, mask=1) at common/channel/channel.cpp:53
#18 0x00000000004bc377 in aeProcessEvents (eventLoop=eventLoop@entry=0x7fa45b6dd0c8, flags=flags@entry=3) at common/channel/redis/ae.c:429
#19 0x00000000004bc7cb in aeMain (eventLoop=0x7fa45b6dd0c8) at common/channel/redis/ae.c:485
#20 0x00000000004aa3f0 in ardb::Thread::ThreadFunc (data=0x7fa45b728b20) at common/thread/thread.cpp:38
#21 0x00007fa45ce316ba in start_thread (arg=0x7fa4451ff700) at pthread_create.c:333
#22 0x00007fa45bc9482d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Not much.


A easy way to reproduce the problem.

Two empty ardb. A(port 16379) and B (port 16380)

set some data on A (set a 1, set b 2....)

loop check  on B :  `while [ 1 ] ; do redis-cli -p 16380 info ;done`

Make B slave of A: redis-cli -p 16379 slaveof 127.0.0.1 16379

After a while, B will crash

**Comment by monsterxx03** [comment]
Awesome! fixed now
