### ISSUE TITLE
Enable `compact-after-snapshot-load` make ardb crashed

### ISSUE THREAD

**Issue by monsterxx03** [yinqiwen/ardb#316]
When set it to true, and `import  dump.rdb` (8GB), after load rdb successfully, ardb start to do compaction and crashed.

```
#0  0x00007f5184eb4428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f5184eb602a in __GI_abort () at abort.c:89
#2  0x00007f5184ef67ea in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7f518500d8a2 "*** %s ***: %s terminated\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007f5184f9756c in __GI___fortify_fail (msg=<optimized out>, msg@entry=0x7f518500d884 "stack smashing detected")
    at fortify_fail.c:37
#4  0x00007f5184f97510 in __stack_chk_fail () at stack_chk_fail.c:28
#5  0x0000000000572756 in ardb::RocksDBLogger::Logv (this=<optimized out>, log_level=<optimized out>,
    format=0x7c00a8 "[%s] Compaction start summary: %s\n", ap=0x7f517d5fbb10) at db/rocksdb/rocksdb_engine.cpp:222
#6  0x000000000064d328 in rocksdb::Log (log_level=log_level@entry=rocksdb::INFO_LEVEL, info_log=...,
    format=format@entry=0x7c00a8 "[%s] Compaction start summary: %s\n") at util/env.cc:199
#7  0x00000000006b5364 in rocksdb::CompactionJob::LogCompaction (this=this@entry=0x7f517d5fc970) at db/compaction_job.cc:1365
#8  0x00000000006ba362 in rocksdb::CompactionJob::Run (this=this@entry=0x7f517d5fc970) at db/compaction_job.cc:518
#9  0x0000000000592e92 in rocksdb::DBImpl::BackgroundCompaction (this=this@entry=0x7f51849f9000,
    made_progress=made_progress@entry=0x7f517d5fd0bf, job_context=job_context@entry=0x7f517d5fd0f0,
    log_buffer=log_buffer@entry=0x7f517d5fd2f0, arg=arg@entry=0x7f516d1fdc00) at db/db_impl.cc:3615
#10 0x00000000005a267e in rocksdb::DBImpl::BackgroundCallCompaction (this=0x7f51849f9000, arg=0x7f516d1fdc00)
    at db/db_impl.cc:3313
#11 0x000000000068beb1 in rocksdb::ThreadPoolImpl::BGThread (this=this@entry=0x7f51848bf800, thread_id=thread_id@entry=10)
    at util/threadpool_imp.cc:229
#12 0x000000000068bfe3 in rocksdb::BGThreadWrapper (arg=0x7f5184843200) at util/threadpool_imp.cc:253
#13 0x00007f5185cf86ba in start_thread (arg=0x7f517d5fe700) at pthread_create.c:333
#14 0x00007f5184f8582d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

frame 10:

info locals:

```
l = {mutex_ = 0x7f51849f94b0}
pending_outputs_inserted_elem = <optimized out>
s = {code_ = rocksdb::Status::kOk, subcode_ = rocksdb::Status::kNone, state_ = 0x0, static msgs = {0x7c7c64 "",
    0x7bdac8 "Timeout Acquiring Mutex", 0x7bdae0 "Timeout waiting to lock key",
    0x7bdb18 "Failed to acquire lock due to max_num_locks limit", 0x7bdafc "No space left on device", 0x0}}
made_progress = false
m = 0x7f516d1fdc00
job_context = {job_id = 4, full_scan_candidate_files = std::vector of length 0, capacity 0,
  sst_live = std::vector of length 0, capacity 0, sst_delete_files = std::vector of length 0, capacity 0,
  log_delete_files = std::vector of length 0, capacity 0, log_recycle_files = std::vector of length 0, capacity 0,
  manifest_delete_files = std::vector of length 0, capacity 0, memtables_to_free = {num_stack_items_ = 0, values_ = {0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, vect_ = std::vector of length 0, capacity 0}, superversions_to_free = {
    num_stack_items_ = 0, values_ = {0x7f5184a00000, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
    vect_ = std::vector of length 0, capacity 0}, logs_to_free = {num_stack_items_ = 0, values_ = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x0}, vect_ = std::vector of length 0, capacity 0}, new_superversion = 0x7f517be34300, manifest_file_number = 0,
  pending_manifest_file_number = 0, log_number = 0, prev_log_number = 0, min_pending_output = 0, prev_total_log_size = 0,
  num_alive_log_files = 0, size_log_to_delete = 0}
log_buffer = {log_level_ = rocksdb::INFO_LEVEL, info_log_ = 0x7f51849bae40, arena_ = {<rocksdb::Allocator> = {
      _vptr.Allocator = 0x7b60a0 <vtable for rocksdb::Arena+16>}, static kInlineSize = 2048, static kMinBlockSize = 4096,
    static kMaxBlockSize = 2147483648,
    inline_block_ = "\272g\255X\000\000\000\000\251q\000\000\000\000\000\000[0] Manual compaction from level-0 to level-1 from (begin) .. (end); will stop at (end)\n", '\000' <repeats 1160 times>..., kBlockSize = 4096,
    blocks_ = std::vector of length 0, capacity 0, huge_blocks_ = std::vector of length 0, capacity 0, irregular_block_num = 0,
    unaligned_alloc_ptr_ = 0x7f517d5fdb08 "", aligned_alloc_ptr_ = 0x7f517d5fd508 "", alloc_bytes_remaining_ = 1536,
    hugetlb_size_ = 0, blocks_memory_ = 2048}, logs_ = {num_stack_items_ = 0, values_ = {0x7f517d5fd308, 0x7f51848bf810, 0x0,
      0x7f5185cfc4ff <__GI___pthread_mutex_unlock+63>, 0x7f517be0d000, 0x7f51849bf110,
      0x68af76 <std::_Hashtable<rocksdb::ThreadStatusData*, rocksdb::ThreadStatusData*, std::allocator<rocksdb::ThreadStatusData*>, std::__detail::_Identity, std::equal_to<rocksdb::ThreadStatusData*>, std::hash<rocksdb::ThreadStatusData*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::_M_rehash(unsigned long, unsigned long const&)+182>, 0xb}, vect_ = std::vector of length 0, capacity 0}}
```

If I manually do `compactall`, it works fine.

**Comment by yinqiwen** [comment]
seems use too many  log buffer to corrupt current stack.  fixed in latest commit.

**Comment by monsterxx03** [comment]
Works now, thanks
