### ISSUE TITLE
Another problem related to compaction during loading rdb

### ISSUE THREAD

**Issue by monsterxx03** [yinqiwen/ardb#317]
After  #316 fixed, load rdb file don't crash anymore.  But I can see error log like following:

```
[11529] 02-23 02:58:24,362 ERROR Invalid key
[11529] 02-23 02:58:24,362 ERROR Invalid key
```

Try to set a breakpoint:  `(gdb) break db/codec.cpp:232`

current KeyObject `type` is 0.

`bt`:

```
#0  ardb::KeyObject::Encode (this=this@entry=0x7fa6047fdf30, buffer=...,
    verify=verify@entry=true, with_ns=with_ns@entry=false) at db/codec.cpp:232
#1  0x000000000056fc70 in ardb::RocksDBEngine::Compact (this=0x7fa61bf2c900,
    ctx=..., start=..., end=...) at db/rocksdb/rocksdb_engine.cpp:1209
#2  0x00000000005366db in ardb::Engine::CompactAll (this=0x7fa61bf2c900, ctx=...)
    at db/engine.cpp:162
#3  0x000000000053b040 in ardb::Ardb::CompactAll (this=0x7ffc210cd230, ctx=...)
    at db/db.cpp:693
#4  0x0000000000558327 in ardb::Snapshot::RedisLoad (this=this@entry=0x7fa6047fe6c0)
    at repl/snapshot.cpp:2204
#5  0x0000000000558610 in ardb::Snapshot::Load (this=this@entry=0x7fa6047fe6c0,
    file="/mnt/dump_14004.rdb",
    cb=cb@entry=0x4bc5b0 <ardb::RDBSaveLoadRoutine(ardb::SnapshotState, ardb::Snapshot*, void*)>, data=data@entry=0x7fa61be7d440) at repl/snapshot.cpp:1690
#6  0x00000000004c69fd in ardb::Ardb::Import (this=0x7ffc210cd230, ctx=..., cmd=...)
    at command/server.cpp:158
#7  0x000000000053b30a in ardb::Ardb::DoCall (this=this@entry=0x7ffc210cd230,
    ctx=..., setting=..., args=...) at db/db.cpp:1395
#8  0x0000000000540ad7 in ardb::Ardb::Call (this=0x7ffc210cd230, ctx=..., args=...)
    at db/db.cpp:1557
#9  0x000000000047416d in ardb::RedisRequestHandler::MessageReceived (e=...,
    ctx=..., this=0x7fa61bf4f300) at network.cpp:130
#10 ardb::ChannelUpstreamHandler<ardb::codec::RedisCommandFrame>::HandleStreamEvent (
    e=..., ctx=..., this=0x7fa61bf4f300)
    at ./common/channel/channel_upstream_handler.hpp:133
```

switch to frame 1, `info locals`:

```
cfp = std::shared_ptr (count 2, weak 0) 0x7fa617eea140
start_buffer = {m_buffer = 0x0, m_buffer_len = 0, m_write_idx = 0, m_read_idx = 0,
  m_in_heap = true, static BUFFER_MAX_READ = 8192, static DEFAULT_BUFFER_SIZE = 32}
end_buffer = {m_buffer = 0x0, m_buffer_len = 0, m_write_idx = 0, m_read_idx = 0,
  m_in_heap = true, static BUFFER_MAX_READ = 8192, static DEFAULT_BUFFER_SIZE = 32}
start_key = {data_ = 0x7c7b64 "", size_ = 0}
end_key = {data_ = 0x7fa6047fde90 "", size_ = 5682788}
opt = {exclusive_manual_compaction = 112, change_level = 222, target_level = 32678,
  target_path_id = 468897024,
  bottommost_level_compaction = (rocksdb::BottommostLevelCompaction::kForce | unknown: 32676)}
s = {code_ = 401501376, subcode_ = 32678,
  state_ = 0x2 <error: Cannot access memory at address 0x2>, static msgs = {
    0x7c7b64 "", 0x7bd9c8 "Timeout Acquiring Mutex",
    0x7bd9e0 "Timeout waiting to lock key",
    0x7bda18 "Failed to acquire lock due to max_num_locks limit",
    0x7bd9fc "No space left on device", 0x0}}
```

If I disable `compact-after-snapshot-load`,  the error log disappeared.

**Comment by yinqiwen** [comment]
fixed in last commit.

**Comment by monsterxx03** [comment]
verified, thanks
