### ISSUE TITLE
A crash coredump

### ISSUE THREAD

**Issue by monsterxx03** [yinqiwen/ardb#358]
```
#0  0x000000000057279a in ardb::RocksDBLogger::Logv (this=<optimized out>, log_level=<optimized out>, format=0x7be42a "%s",
    ap=0x7f31891fdf30) at db/rocksdb/rocksdb_engine.cpp:222
#1  0x000000000064d238 in rocksdb::Log (log_level=log_level@entry=rocksdb::WARN_LEVEL,
    info_log=std::shared_ptr (count 3, weak 0) 0x7f31941bae20, format=format@entry=0x7be42a "%s") at util/env.cc:199
#2  0x000000000057db92 in rocksdb::DBImpl::MaybeDumpStats (this=this@entry=0x7f318e675000) at db/db_impl.cc:639
#3  0x00000000005a26b6 in rocksdb::DBImpl::BackgroundCallCompaction (this=0x7f318e675000, arg=0x0) at db/db_impl.cc:3296
#4  0x000000000068be01 in rocksdb::ThreadPoolImpl::BGThread (this=this@entry=0x7f31940bf800, thread_id=thread_id@entry=15)
    at util/threadpool_imp.cc:229
#5  0x000000000068bf33 in rocksdb::BGThreadWrapper (arg=0x7f3194044120) at util/threadpool_imp.cc:253
#6  0x00007f31954e76ba in start_thread (arg=0x7f31891ff700) at pthread_create.c:333
#7  0x00007f31947743dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

f 3 
info locals

```
made_progress = false
m = 0x0
job_context = {job_id = 124, full_scan_candidate_files = std::vector of length 0, capacity 0,
  sst_live = std::vector of length 0, capacity 0, sst_delete_files = std::vector of length 0, capacity 0,
  log_delete_files = std::vector of length 0, capacity 0, log_recycle_files = std::vector of length 0, capacity 0,
  manifest_delete_files = std::vector of length 0, capacity 0, memtables_to_free = {num_stack_items_ = 0, values_ = {0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, vect_ = std::vector of length 0, capacity 0}, superversions_to_free = {
    num_stack_items_ = 0, values_ = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, vect_ = std::vector of length 0, capacity 0},
  logs_to_free = {num_stack_items_ = 0, values_ = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
    vect_ = std::vector of length 0, capacity 0}, new_superversion = 0x7f3194031000, manifest_file_number = 0,
  pending_manifest_file_number = 0, log_number = 0, prev_log_number = 0, min_pending_output = 0, prev_total_log_size = 0,
  num_alive_log_files = 0, size_log_to_delete = 0}
log_buffer = {log_level_ = rocksdb::DEBUG_LEVEL, info_log_ = 0x0, arena_ = {<rocksdb::Allocator> = {_vptr.Allocator = 0x0},
    static kInlineSize = 2048, static kMinBlockSize = 4096, static kMaxBlockSize = 2147483648,
    inline_block_ = '\000' <repeats 1696 times>..., kBlockSize = 7581250,
    blocks_ = std::vector of length 23069077, capacity 23069402 = {0x1 <error: Cannot access memory at address 0x1>,
      0x7f318e64d000 "", 0xc9d0 <error: Cannot access memory at address 0xc9d0>,
      0x93f0 <error: Cannot access memory at address 0x93f0>, 0x0, 0x7f3194200140 "", 0x7f3194200140 "",
      0x7f31941c8800 "\327\003", 0x10 <error: Cannot access memory at address 0x10>,
      0x1 <error: Cannot access memory at address 0x1>, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x7f3194076300 "", 0x7f31941bf0e0 "0\217{", 0x1 <error: Cannot access memory at address 0x1>, 0x0, 0x7f31891ff700 "",
      0x7f319407c410 "\001", 0x7f31891ff700 "", 0x1 <error: Cannot access memory at address 0x1>, 0x0,
      0x66b700ef6e966c00 <error: Cannot access memory at address 0x66b700ef6e966c00>,
      0x9ccde51d133c5ee4 <error: Cannot access memory at address 0x9ccde51d133c5ee4>, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x7f3189dfe9c0 "\300\371_\212\061\177", 0x7f317bdff9c0 "\300\371\037\211\061\177",
      0x83400000845 <error: Cannot access memory at address 0x83400000845>, 0x7f31891ff9e0 "\340\371\037\211\061\177",
      0x7f31891ff9e0 "\340\371\037\211\061\177", 0xffffffffffffffe0 <error: Cannot access memory at address 0xffffffffffffffe0>,
      0x0, 0x0, 0x7f31891fecb0 "", 0x0, 0x1 <error: Cannot access memory at address 0x1>, 0x7f31891ff498 "\001", 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0...},
    huge_blocks_ = std::vector of length 8740682203152, capacity 1628 = {<error reading variable>, logs_ = {
    num_stack_items_ = 18446744073709551000, values_ = {0x0, 0x7f31940bf810, 0x0,
      0x7f31954eb4ff <__GI___pthread_mutex_unlock+63>, 0x7f31891ff700, 0x7f318e64d000, 0x72d94b <malloc+1131>, 0x0},
    vect_ = std::vector of length 8989717913403680, capacity 11070240 = {0x7f31891ff700, 0x7f319407c410, 0x7f31891ff700, 0x1,
      0x0, 0x66b700ef6e966c00, 0x9ccde51d133c5ee4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7f3189dfe9c0, 0x7f317bdff9c0,
      0x83400000845, 0x7f31891ff9e0, 0x7f31891ff9e0, 0xffffffffffffffe0, 0x0, 0x0, 0x7f31891fecb0, 0x0, 0x1, 0x7f31891ff498,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7f31891ffa10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
      0x1, 0x0, 0x810d0037b558f2, 0x0, 0x0, 0x0...}}}
```

Haven't  reproduced it yet

**Comment by monsterxx03** [comment]
Seems like this one:  #356 ,  haven't tried the patch, will upgrade to test.
