### ISSUE TITLE
Crash: multi-clients (4 clients) do mget()

### ISSUE THREAD

**Issue by squalfof** [yinqiwen/ardb#383]
Rocksdb Engine, mget.key_count == 50, 4 clients

Following is the stack backtrace,

```
#0  je_rtree_get (dependent=true, key=<optimized out>, rtree=<optimized out>) at include/jemalloc/internal/rtree.h:325
#1  je_chunk_lookup (dependent=true, ptr=<optimized out>) at include/jemalloc/internal/chunk.h:89
#2  huge_node_get (ptr=<optimized out>) at src/huge.c:11
#3  je_huge_salloc (tsdn=<optimized out>, ptr=<optimized out>) at src/huge.c:434
#4  0x00000000006c6611 in usable_size (this=<optimized out>) at ./table/block.h:166
#5  rocksdb::BlockBasedTable::PutDataBlockToCache (block_cache_key=..., compressed_block_cache_key=..., block_cache=block_cache@entry=0x1386018, block_cache_compressed=block_cache_compressed@entry=0x0, read_options=..., ioptions=..., block=block@entry=0x7fffd27fdb00,
    raw_block=<optimized out>, format_version=2, compression_dict=..., read_amp_bytes_per_bit=0) at table/block_based_table_reader.cc:1067
#6  0x00000000006c7575 in rocksdb::BlockBasedTable::MaybeLoadDataBlockToCache (rep=rep@entry=0x1390a80, ro=..., handle=..., compression_dict=..., block_entry=block_entry@entry=0x7fffd27fdb00) at table/block_based_table_reader.cc:1406
#7  0x00000000006c7725 in rocksdb::BlockBasedTable::NewDataBlockIterator (rep=0x1390a80, ro=..., index_value=..., input_iter=input_iter@entry=0x7fffd27fddd0) at table/block_based_table_reader.cc:1313
#8  0x00000000006ca355 in rocksdb::BlockBasedTable::Get (this=0x1368de0, read_options=..., key=..., get_context=0x7fffd27fe230, skip_filters=<optimized out>) at table/block_based_table_reader.cc:1637
#9  0x00000000005fe415 in rocksdb::TableCache::Get (this=0x1367720, options=..., internal_comparator=..., fd=..., k=..., get_context=get_context@entry=0x7fffd27fe230, file_read_hist=0x13e8d60, skip_filters=false, level=2) at db/table_cache.cc:330
#10 0x00000000006123fd in rocksdb::Version::Get (this=0x13a8c00, read_options=..., k=..., value=value@entry=0x1aa81d8, status=status@entry=0x1aa4d70, merge_context=merge_context@entry=0x7fffd27fe3a0, range_del_agg=range_del_agg@entry=0x7fffd27fe3e0,
    value_found=value_found@entry=0x0, key_exists=key_exists@entry=0x0, seq=seq@entry=0x0) at db/version_set.cc:963
#11 0x000000000059afd6 in rocksdb::DBImpl::MultiGet (this=0x13c2000, read_options=..., column_family=std::vector of length 50, capacity 64 = {...}, keys=std::vector of length 50, capacity 50 = {...}, values=0x13aec48) at db/db_impl.cc:4162
#12 0x0000000000576fdb in ardb::RocksDBEngine::MultiGet (this=0x1277400, ctx=..., keys=..., values=std::vector of length 50, capacity 50 = {...}, errs=...) at db/rocksdb/rocksdb_engine.cpp:972
#13 0x000000000051be1b in ardb::Ardb::MGet (this=0x7fffffffdd10, ctx=..., cmd=...) at command/t_string.cpp:65
#14 0x0000000000544abe in ardb::Ardb::DoCall (this=this@entry=0x7fffffffdd10, ctx=..., setting=..., args=...) at db/db.cpp:1395
#15 0x0000000000548940 in ardb::Ardb::Call (this=0x7fffffffdd10, ctx=..., args=...) at db/db.cpp:1557
#16 0x00000000004994d6 in ardb::RedisRequestHandler::MessageReceived (this=0x13fa8f0, ctx=..., e=...) at network.cpp:130
#17 0x0000000000493053 in HandleStreamEvent (e=..., ctx=..., this=<optimized out>) at ./common/channel/channel_upstream_handler.hpp:133
#18 ardb::ChannelPipeline::SendUpstream<ardb::codec::RedisCommandFrame> (ctx=<optimized out>, e=..., this=<optimized out>) at ./common/channel/all_includes.hpp:89
#19 0x0000000000499c8e in SendUpstream<ardb::MessageEvent<ardb::codec::RedisCommandFrame> > (this=<optimized out>, this=<optimized out>, e=...) at ./common/channel/all_includes.hpp:164
#20 fire_message_received<ardb::codec::RedisCommandFrame> (destructor=0x0, message=0x7fffd27fea20, ctx=...) at ./common/channel/channel_helper.hpp:91
#21 ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::CallDecode (this=<optimized out>, context=..., channel=0x14a45a0, cumulation=..., this=<optimized out>, this=<optimized out>) at ./common/channel/codec/stack_frame_decoder.hpp:102
#22 0x0000000000499fcf in ardb::codec::StackFrameDecoder<ardb::codec::RedisCommandFrame>::MessageReceived (this=0x1df7280, ctx=..., e=...) at ./common/channel/codec/stack_frame_decoder.hpp:157
#23 0x00000000004a7043 in HandleStreamEvent (e=..., ctx=..., this=<optimized out>) at ./common/channel/channel_upstream_handler.hpp:133
#24 ardb::ChannelPipeline::SendUpstream<ardb::Buffer> (ctx=<optimized out>, e=..., this=<optimized out>) at ./common/channel/all_includes.hpp:89
#25 0x00000000004a854e in SendUpstream<ardb::MessageEvent<ardb::Buffer> > (event=..., this=0x14a45d8) at ./common/channel/all_includes.hpp:128
#26 fire_message_received<ardb::Buffer> (destructor=0x0, message=0x14a4608, channel=0x14a45a0) at ./common/channel/channel_helper.hpp:83
#27 ardb::Channel::OnRead (this=0x14a45a0) at common/channel/channel.cpp:560
#28 0x00000000004a6e5d in ardb::Channel::IOEventCallback (eventLoop=<optimized out>, fd=<optimized out>, clientData=0x14a45a0, mask=1) at common/channel/channel.cpp:53
#29 0x00000000004db640 in aeProcessEvents (eventLoop=eventLoop@entry=0x7ffff5a8f198, flags=flags@entry=3) at common/channel/redis/ae.c:429
#30 0x00000000004db90b in aeMain (eventLoop=0x7ffff5a8f198) at common/channel/redis/ae.c:485
#31 0x00000000004c9f40 in ardb::Thread::ThreadFunc (data=0x3a1cb10) at common/thread/thread.cpp:38
#32 0x00007ffff7bc8dc5 in start_thread () from /lib64/libpthread.so.0
#33 0x00007ffff61be76d in clone () from /lib64/libc.so.6
```

Any suggestions ? Thanks.

**Comment by yinqiwen** [comment]
same crash problem caused by jemalloc (https://github.com/antirez/redis/issues/3471)   
maybe we should upgrade jemalloc to latest version to test

**Comment by squalfof** [comment]
Remove deps on jemalloc, works well, no crash any more.

P.S.: tried jemalloc-4.5.0, still crash; tried jemalloc-5.0.0, fail to compile. So i just use the most direct way -- to disable jemalloc.  Anyway, yes, it's caused by jemalloc. Waiting for your update to a workable jemalloc version 👍

**Comment by yinqiwen** [comment]
just upgrade jemalloc to 5.0.1,  can u test again for this issue?

**Comment by squalfof** [comment]
retest, still crash. run ```ldd ardb-server```,  ```libtcmalloc.so.4``` is needed.
not sure if it relates to my env ?

**Comment by yinqiwen** [comment]
seems rocksdb detect tcmalloc installed and use it,  but ardb link jemalloc static to replace defaule malloc which may cause some unexpected problem.

**Comment by squalfof** [comment]
in that case, sounds Makefile should test if tcmalloc exists already.
